### ISSUE TITLE
Reading and setting headers

### ISSUE THREAD

**Issue by AlexLepauvre** [holgern/pyedflib#101]
Dear all,

I have been using the pyedflib to chop EDF files, as one of my project requires a recorded EDF files to be chopped in sub files.  While the chopping and saving to separate files runs very smoothly, i am facing issues in setting the headers. What I am trying to do is to use the headers from the original file to create the headers of the subfolders (I am talking about the file headers as opposed to the signal header). The first issue I am facing is that the pyedflib doesn't seem to recognize the headers of the original file, while edf browser and custom matlab function do. The headers are surprisingly empty when reading them using the following commands:

```
edf_file_handle = pyedflib.EdfReader(file_name, 0, 0)
header = edf_file_handle.getHeader() 
```

The header variable return the correct format, but all the entries within it are empty, to the exception of the date and time. Has anyone encountered similar issues?

The second issue emerges when I attempt to create entries in the Participant Name and code. Our project requires these headers to be anonymize in a specific fashion, I am therefore performing the anonymization manually as I am generating the sub files. However, while the files do get saved and can be loaded back up, the headers end up being really messed up, everything gets displaced. I am using the following code to do so:

```
# First open the EDF writer file:
o = pyedflib.EdfWriter(file_name, n_electrodes)
# Set the file headers to the headers found in the original file:
o.setHeader(controller.edf_file_handle.getHeader())
# Set the Patient Name to X X X X_X + padding to make up to the specified 80 chars;
o.setPatientName('X X X X_X' + ' '*(80-len('X X X X_X')))
# Set the Patient code to X X X X_X + padding to make up to the specified 80 chars;
o.setPatientCode('X X X X_X' + ' '*(80-len('X X X X_X')))
# Change the date to some specified date:
new_datetime = datetime("SOME_SPECIFIED_DATE)
o.setStartdatetime(new_datetime )
```
I am guessing the two issues are somewhat related, and I am guessing that it might be due to the way of formatting of the headers I use to replace the ones in the original file, and that it might be displacing the rest of the headers, but I couldn't find any fix for both issues.

I am also unable to share any of the concerned EDF files, for data privacy reasons.

Kind regards,

Alex

**Comment by skjerns** [comment]
If you are able to, you can send a sample file and script anonymously to mllfbaul95p@temp.mailbox.org , I will handle it confidentially.

Without the files it will be a bit more difficult to reconstruct what is going wrong. Maybe you can reconstruct a case that mimics yours?

**Comment by AlexLepauvre** [comment]
Dear skjerns,

Unfortunately, sharing a file of mine isn't an option. I am currently trying to simulate data of mine, I will forward those as soon as I made it. 

I was also wondering whether there are specific format expectations about how to enter the patient code and names? In a similar function I created in matlab, there were some specific things, for example, no numbers accepted, the string should be systematically 80 chars long and horizontal orientation and so on. Anything similar here or is pyedflib more flexible in terms of input?

Kind regards,

Alex

**Comment by AlexLepauvre** [comment]
I generated a sample file. I could only mimick the second part of the issue. The file was created using the following code:
```
import pyedflib
from datetime import datetime, date
import numpy as np

# Generating an EDF file with 1 chan
f = pyedflib.EdfWriter('test.edf', 1)
# Setting random birthdate
f.setBirthdate(date(1951, 8, 2))
# Setting patient name
f.setPatientName("X X X **X_X"+ ' '*(80-len('X X X X_X')))
# Setting patient code:
f.setPatientCode("X X X X_X"+ ' '*(80-len('X X X X_X')))

# Creating a np.array of zeros to populate the file:
sigbuf = np.zeros((1, 2048), dtype=np.int32)
# Writing the data to file:
f.writeSamples(sigbuf, digital=True)
# Closing the file
f.close()
```
I would therefore expect the participant name and code to be X X X X_X while the birthdate should be to what I set. However, it seems that things get misplaced. When reading the saved file again, it gives me the following headers (among other):
![image](https://user-images.githubusercontent.com/54275933/105046447-68b9b900-5a69-11eb-8727-32c20983eec3.png)

Similarily, in edfbrowser, I see the following:
![image](https://user-images.githubusercontent.com/54275933/105046563-8ab33b80-5a69-11eb-9746-32616a409709.png)

Here is the file attached:
[test.zip](https://github.com/holgern/pyedflib/files/5836414/test.zip)

**Comment by skjerns** [comment]
just remove the `' '*(80-len('X X X X_X')` part and then it works fine :)

the padding is done automatically. However, there is indeed a warning lacking if the header entries are too long. I will add that.

**Comment by AlexLepauvre** [comment]
Thanks a lot, it worked perfectly. This was all a big misunderstanding. I was under the impression that setPatientName would set the 'local patient identification', and I was looking in the pyedflib documentation for direct equivalence to the edf headers. However, these different functions set part of headers, right? For example, setPatientName would set the patient name in the local patient identification, setBirthDate will set the birth date in the local patient identification as well but setTechnician would set the technician ID within the local recording identification and so on. That's why I was trying to pass 'X X X X_X', each X would be one of the part of the headers set by the different functions.

All is solved, thanks a lot for the amazing support (and apologies for the misunderstanding)!

Kind regards,

Alex
