### ISSUE TITLE
Take hours/days to write signals into edf file using highlevel.write_edf?

### ISSUE THREAD

**Issue by lisonglu** [holgern/pyedflib#105]
`#load .mat file
mat = mat73.loadmat('XXX.mat')
signals = mat['data'] #signals
#signals = signals[~np.isnan(signals)] #drop nans(we don't want to lose information)
signals[np.isnan(signals)] = -99999 #make nans as super big value(so that artifact removal code will mark it as artifact)
channel_names = mat['channels'] #channels
Fs = mat['Fs'] #array
signal_headers = highlevel.make_signal_headers(channel_names, sample_rate=Fs, physical_max = 100000, physical_min = -100000)
header = highlevel.make_header(patientname='patient_of_xxx')
# write signals into edf file(this step takes long......)
highlevel.write_edf('XXX.edf', signals, signal_headers, header)`

Hi,
I am using pyedflib to convert .mat file .edf. It takes hours to generate a 10,000kb edf file and days to generate a 100,000kb file. 
Is that normal? Is there anything that I can do to accelerate this process?
Thanks for any help!

**Comment by skjerns** [comment]
No, this is not normal. However, without the source data I cannot replicate this. Can you upload the matfile to wetransfer?

Some things for debugging:
1) can you let me know the array dimensions of signals? 
2) can you create an array with `signals=np.random.randn(x,x,x)` with the same shape and see if the problem persists?
3) Whats the resulting file size?

**Comment by lisonglu** [comment]
https://drive.google.com/file/d/1-rQqO8UUUOVajWSnsTxr9MZuxhgnj-JA/view?usp=sharing
This is a sample .mat file. Sorry if it's a little bit large. (taking about 5 mins to download)
I believe the converted EEG file will be larger than 1,000,000kb.
We set the Nans to -99999 because most artifact removal code will mark a super large value as an artifact, kind of necessary for future study. 
Can you please try my code and see if there is any bug making it slow?(My code will take days to process this sample file)
Thank you!

**Comment by skjerns** [comment]
On preliminary runs, it seems that the writing time does not increase linearly with the data, which is strange, it indeed painfully slow. I have successfully written large files (24h) before and it was not that slow - I need to investigate this, very strange.

**Comment by lisonglu** [comment]
OMG. Thank you so much for doing this! It works well after changing signals to C order.

**Comment by skjerns** [comment]
happy to help and also to learn something new myself :))
