### ISSUE TITLE
Highlevel reading and writing again leads to write_edf failing with AssertionError on phys_min and signal_min

### ISSUE THREAD

**Issue by benelot** [holgern/pyedflib#108]
When trying a sanity check on one of my edf files, I received an AssertionError with a minor deviation of mins:

> AssertionError: phys_min is -5482.28, but signal_min is -5482.447311136204 for channel EEG DE1_1-Ref

The sanity check if the following:

```
file = "./data/1.edf"

signals, signal_headers, header = highlevel.read_edf(file, verbose=True)

file_copy = "./data/1_c.edf"

highlevel.write_edf(file_copy, signals=signals, signal_headers=signal_headers, header=header)

highlevel.compare_edf(file, file_copy)
```

Should this not be able to pass easily? Is there anything I am doing wrong here?

Edit: Problem also occurs when I drop channels wit the highlevel interface, which runs with digital=True:
AssertionError: digital_min is -32767, but signal_min is -32768for channel EEG DE1_1-Ref

**Comment by benelot** [comment]
There is a second issue I encountered after I copied the highlevel function from the repo and removed the assertion:

I received a problem that some the duration_in_seconds of the annotations were read in byte form instead of integers and thus could not be written back to the edf file. Here I wrote a little snippet that checks and transforms the annotations' duration_in_seconds and allows it to be written back to disk.

```
for index1, l in enumerate(header["annotations"]):
    for index2, e in enumerate(l):
        if isinstance(e, (bytes, bytearray)):
            print(i, e)
            e = e.decode("utf-8")
            e = float(e)
            print(index2)
            header["annotations"][index1][index2] = e

print("----")
for l in header["annotations"]:
    print(l[1])
```

**Comment by skjerns** [comment]
This is something that I have been struggeling myself with as well before I joined the development here. Using `digital=True` resolved the issue for me in almost all cases, expect for cases when the values in the file exceeded `physical_max/min`. But you are right, this should probably not happen.

Are you able to share the file with me for debugging purposes? (e.g wetransfer)

**Comment by benelot** [comment]
Really unfortunately not at all as it is from our internal measurements that are not published and sharable with people outside of the group.

**Comment by benelot** [comment]
I will see if I can extract a very short file that still has the same issue and then annonymize it so that you can use it for debugging.

**Comment by skjerns** [comment]
Any update on a testfile with code so I can replicate the problem?

**Comment by benelot** [comment]
Hi! I was able to reproduce the problem on a simple basis, but I can not send you an edf file of it, because I am only working with your code and write_edf seems to recalculate the physical_min and then the problem dissapears. However, I saved the data I extracted from my edf into a pickle file which I can load and then save it again as edf which makes the problem occur:

```
signal_sample = np.load(f"./test.npy")
signal_headers = [{'sample_rate': 1024, 'physical_max': 5482.288, 'physical_min': -5482.28, 'digital_max': 32767, 'digital_min': -32767, 'dimension': 'uV', 'transducer': '', 'prefilter': 'HP:0.010 Hz LP:70.0 Hz N:0.0',"label": str(i)} for i in range(len(signal_hour))]
highlevel.write_edf(f"./test.edf" , signals=signal_sample, signal_headers=signal_headers)

```
Running this will give me the output:
```
    AssertionError: phys_min is -5482.28, but signal_min is -5482.447311136204 for channel 0
```


I am not sure if this will help with it as it seems that the phys_min as set in the header read from the file is just different from the signal_sample content. 

I am just checking how to provide you with the test.npy

**Comment by benelot** [comment]
https://www.dropbox.com/s/0cm5tmuv5v8cgy4/test.npy?dl=0

**Comment by skjerns** [comment]
Ok, but when you load the original file it states a signal_min of `5482.28`? 
Can you send me the header/signal headers of the original file?

My hunch is that the file has been created with the digital min set to -32,767, however, the file contains values up to -32,768 (this quite often happens actually, as a programming error from other libraries). Can you check this by loading the data with `digital=True` and check if values of `-32768` occur? This way the calculation are out of bounds, and the sanity check of `edflib` rejects the writing of the file.

**Comment by benelot** [comment]
The header I am creating in the code is basically the compact representation of the original header. Does that already answer your question?

**Comment by benelot** [comment]
If not, I will load it with digital=True tomorrow.

**Comment by skjerns** [comment]
> The header I am creating in the code is basically the compact representation of the original header. Does that already answer your question?

More or less, yes!



> If not, I will load it with digital=True tomorrow.

You can just use this snipped and paste the result
```Python
signals, sheaders, header = highlevel.read_edf('file.edf', digital=True)
for s, sh in zip(signals, sheaders):
    print(f'sh["label"] d: {sh["digital_min"]}/{sh["digital_max"]}, p: {sh["physical_min"]:.2f}/{sh["physical_max"]:.2f}, data: {s.min()}/{s.max()}')
```

**Comment by benelot** [comment]
Here you go:
```
sh["label"] d: -32767/32767, p: -5482.28/5482.29, data: -32768/32767
sh["label"] d: -32767/32767, p: -5482.28/5482.29, data: -32768/32767
sh["label"] d: -32767/32767, p: -5482.28/5482.29, data: -32768/32767
sh["label"] d: -32767/32767, p: -5482.28/5482.29, data: -32768/32767
sh["label"] d: -32767/32767, p: -5482.28/5482.29, data: -32768/32767
sh["label"] d: -32767/32767, p: -5482.28/5482.29, data: -32768/32767
sh["label"] d: -32767/32767, p: -5482.28/5482.29, data: -32768/32767
sh["label"] d: -32767/32767, p: -5482.28/5482.29, data: -32768/32767
sh["label"] d: -32767/32767, p: -5482.28/5482.29, data: -32768/32767
sh["label"] d: -32767/32767, p: -5482.28/5482.29, data: -32768/32766
sh["label"] d: -32767/32767, p: -5482.28/5482.29, data: -32768/32767
sh["label"] d: -32767/32767, p: -5482.28/5482.29, data: -32768/32767
sh["label"] d: -32767/32767, p: -5482.28/5482.29, data: -32768/32767
sh["label"] d: -32767/32767, p: -5482.28/5482.29, data: -32768/32767
sh["label"] d: -32767/32767, p: -5482.28/5482.29, data: -32768/32765
sh["label"] d: -32767/32767, p: -5482.28/5482.29, data: -32768/32756
sh["label"] d: -32767/32767, p: -5482.28/5482.29, data: -32768/32767
sh["label"] d: -32767/32767, p: -5482.28/5482.29, data: -32768/32765
sh["label"] d: -32767/32767, p: -5482.28/5482.29, data: -32768/32765
sh["label"] d: -32767/32767, p: -5482.28/5482.29, data: -32768/32765
sh["label"] d: -32767/32767, p: -5482.28/5482.29, data: -32768/32763
sh["label"] d: -32767/32767, p: -5482.28/5482.29, data: -32768/32765
sh["label"] d: -32767/32767, p: -5482.28/5482.29, data: -32768/32767
sh["label"] d: -32767/32767, p: -5482.28/5482.29, data: -32768/32764
sh["label"] d: -32767/32767, p: -5482.28/5482.29, data: -32768/32763
sh["label"] d: -32767/32767, p: -5482.28/5482.29, data: -32768/32767
sh["label"] d: -32767/32767, p: -5482.28/5482.29, data: -32768/32767
sh["label"] d: -32767/32767, p: -5482.28/5482.29, data: -32768/32767
sh["label"] d: -32767/32767, p: -5482.28/5482.29, data: -32768/32767
sh["label"] d: -32767/32767, p: -5482.28/5482.29, data: -32768/32767
sh["label"] d: -32767/32767, p: -5482.28/5482.29, data: -32768/32767
sh["label"] d: -32767/32767, p: -5482.28/5482.29, data: -32768/32766
sh["label"] d: -32767/32767, p: -5482.28/5482.29, data: -14633/32496
sh["label"] d: -32767/32767, p: -5482.28/5482.29, data: -32636/6423
sh["label"] d: -32767/32767, p: -5482.28/5482.29, data: -14607/32672
sh["label"] d: -32767/32767, p: -5482.28/5482.29, data: -32768/4654
sh["label"] d: -32767/32767, p: -5482.28/5482.29, data: -32324/7698
sh["label"] d: -32767/32767, p: -5482.28/5482.29, data: -32768/4611
sh["label"] d: -32767/32767, p: -5482.28/5482.29, data: -32557/10378
sh["label"] d: -32767/32767, p: -5482.28/5482.29, data: -15011/24420
sh["label"] d: -32767/32767, p: -5482.28/5482.29, data: -9017/32671
sh["label"] d: 0/9, p: 0.00/9.00, data: 0/9
```

**Comment by skjerns** [comment]
Ah yes, just as I expected: The original headers have a wrong digital minimum setup. Probably the programmer of the software that created the file thought that `int16` minimum is just int16 maximum with a minus before. 

I think it will be safest to load the values with `digital=True`, then save it again with the correct digital minimum (`-32768`) and with the adapted physical minimum (`signal.min()`).

**Comment by benelot** [comment]
Ok thanks! The file was created by the software of the iEEG measurement
device we have in our hospital, but this might well be as you describe.
Thanks for the advice, I currently load from it and cut it up into smaller
one hour pieces, so that step can be easily included.

**Comment by skjerns** [comment]
Happy to help :) good luck with your research!
