### ISSUE TITLE
highlevel.read_edf fails with ValueError

### ISSUE THREAD

**Issue by bdlabitt** [holgern/pyedflib#109]
highlevel.read_edf_header reads my file.  highlevel.read_edf fails with ValueError.
`import pyedflib as edf
f1 = "20201224_230415_PLD.edf"

mydict1 = edf.highlevel.read_edf_header(f1) # this works fine

# next line does not!
signals, signal_headers, header = edf.highlevel.read_edf(f1, digital=False, verbose=True)
`
I can send the edf file.  It is 435KB.  It is from a commercial machine.  File can be read by edfbrowser, although there are multiple units in the file (like L/s, cm-H20, unitless).  Didn't know if this site would allow such a large file to be attached.

I can't seem to read individual channels, as there is insufficient documentation on this library.  All my attempts have failed.  Lots of examples using a test generator, but none just opening a pre-existing file and examining data.  Although there is a close method, there doesn't appear to be an open method - or it's not described clearly.

This simple code example does work for a 5MB file made by the same machine.  I've used it to plot high resolution flow data using matplotlib.

**Comment by skjerns** [comment]
1) What's the error message that you get?

2) You can upload the file to https://easyupload.io and set expiration to 30 days or forever, I can have a look.

The docstrings of the function give you hints: `read_edf(f1, ch_nrs=[0, 1])`, that should work

**Comment by bdlabitt** [comment]
1.
In [1]: run testedf.py
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/Apps/pyEDFLib/testedf.py in <module>
      7 
      8 # next line does not!
----> 9 signals, signal_headers, header = edf.highlevel.read_edf(f1, digital=False, verbose=True)
     10 

~/Apps/pyEDFLib/pyedf/lib/python3.8/site-packages/pyedflib/highlevel.py in read_edf(edf_file, ch_nrs, ch_names, digital, verbose)
    369         if all_sfreq_same:
    370             dtype = np.int32 if digital else np.float
--> 371             signals = np.array(signals, dtype=dtype)
    372 
    373     assert len(signals)==len(signal_headers), 'Something went wrong, lengths'\

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (14,) + inhomogeneous part.

In [2]: 
2. In progress.  Will post when ready.
3. Missed the fact that ch_nrs and ch_names are a list.  Thanks for the tip.  That works!
Curious why reading the whole file fails.  Seems to fail reading the CRc16 part of the file.

**Comment by bdlabitt** [comment]
https://easyupload.io/0gue2t
password: pyedflib_testfile50%

**Comment by skjerns** [comment]
I checked the file. Appareantly the sample rate is calculated incorrectly due to a (literal) rounding error. I'll fix it.

Can you let me know what the original sample frequencies of the channel are? they are currently reported by pyedflib as 0.5 Hz.

**Comment by bdlabitt** [comment]
The sample rate should be 0.5 Hz.  (To the best of my knowledge.)

**Comment by bdlabitt** [comment]
What's the best way for me to test this?  I originally did a pip3 install in a virtual environment called pyedf.  I've built from source before, (other projects) but not under a venv.

**Comment by skjerns** [comment]
you can just install directly from github `pip install git+https://github.com/holgern/pyedflib.git`. This requires git and a compiler to be installed.

**Comment by bdlabitt** [comment]
I have gcc, g++ and git on my system.  Do I need to install this in the venv?  If so, not sure how to do this.  Trying to keep pyedflib in a venv until I have everything sorted.  My system Numpy is 1.17.4 whereas my venv Numpy is at 1.20.1.  If I am understanding correctly, I just have to be in the venv and type pip3 install git+https://github.com/holgern/pyedflib.git ?

Thanks for making the changes.  Right now, I only need to be able to read edfs.
