### ISSUE TITLE
Support signals with duration 0 requested

### ISSUE THREAD

**Issue by bdlabitt** [holgern/pyedflib#112]
Commercial product (PAP machines by a major world wide manufacturer >> 2Million machines) writes apnea events to edf file.  Sometimes, as in the case of hypopnea, it is difficult for the machine (with it's limited resources) to determine the actual duration of the event.  In that case the machine writes a 0 for the duration.  Current version of pyEDFLib (and edfbrowser) fail on these files.  The file cannot be opened. What is important for viewing applications is when the each event occured (which the machine records), what kind of apnea it was.  The viewing application displays these apnea events are super-imposed on the high resolution flow waveforms.  Apnea occurs at random times, there is no effective sample rate.  It really is just an event.  It would be good for pyEDFLib to be able to read in these events.

```Python
import pyedflib as edf
f3 = '20201224_230408_EVE.edf'
mydict3 = edf.highlevel.read_edf_header(f3)
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-4-49ce677c6ca0> in <module>
----> 1 mydict3 = edf.highlevel.read_edf_header(f3)

~/Apps/pyEDFLib/pyedf/lib/python3.8/site-packages/pyedflib/highlevel.py in read_edf_header(edf_file, read_annotations)
    543     """
    544     assert os.path.isfile(edf_file), 'file {} does not exist'.format(edf_file)
--> 545     with pyedflib.EdfReader(edf_file) as f:
    546 
    547         summary = f.getHeader()

pyedflib/_extensions/_pyedflib.pyx in pyedflib._extensions._pyedflib.CyEdfReader.__init__()
pyedflib/_extensions/_pyedflib.pyx in pyedflib._extensions._pyedflib.CyEdfReader.open()
pyedflib/_extensions/_pyedflib.pyx in pyedflib._extensions._pyedflib.CyEdfReader.check_open_ok()

OSError: 20201224_230408_EVE.edf: The file is discontinous and cannot be read

signals, signal_headers, header = edf.highlevel.read_edf(f3, ch_nrs=mylist, digi
   ...: tal=False, verbose=True)
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-5-4947d3b49bdd> in <module>
----> 1 signals, signal_headers, header = edf.highlevel.read_edf(f3, ch_nrs=mylist, digital=False, verbose=True)

~/Apps/pyEDFLib/pyedf/lib/python3.8/site-packages/pyedflib/highlevel.py in read_edf(edf_file, ch_nrs, ch_names, digital, verbose)
    326         not isinstance(ch_names, list): ch_names = [ch_names]
    327 
--> 328     with pyedflib.EdfReader(edf_file) as f:
    329         # see which channels we want to load
    330         available_chs = [ch.upper() for ch in f.getSignalLabels()]

pyedflib/_extensions/_pyedflib.pyx in pyedflib._extensions._pyedflib.CyEdfReader.__init__()
pyedflib/_extensions/_pyedflib.pyx in pyedflib._extensions._pyedflib.CyEdfReader.open()
pyedflib/_extensions/_pyedflib.pyx in pyedflib._extensions._pyedflib.CyEdfReader.check_open_ok()

OSError: 20201224_230408_EVE.edf: The file is discontinous and cannot be read
```
I can post the EVE file if requested.  It is 1.2kB.  The actual events are discontinuous, that's how real life is sometimes.
Doesn't matter if the number of channels is supplied, (mylist) even if None, the same OSError is created.

**Comment by skjerns** [comment]
If EDFBrowser (which uses `edflib`) can't read it, it's unfortunately unlikely that we can provide a fix for that, as we are also using `edflib` in the background (`pyedflib` is just a Python wrapper for `edflib`). In this case it might be better to ask the question at [gitlab/edflib/edfbrowser](https://gitlab.com/users/Teuniz/projects)

However, the error message rather points to the file being a "edf+c" file, which is currently not supported, sorry.

**Comment by bdlabitt** [comment]
https://easyupload.io/j6ccyi
pwd: pyedflib_testfile50%

Gee, what the heck is an edf+c file?  I can barely grasp edf and edf+ 
I can ask at gitlab/edflib/edfbrowser

Using ghex, I see EDF+D in the file.  Are there any EDF+D readers?

**Comment by skjerns** [comment]
edit: sorry a `not` was missing.

EDF+D is discontinuous, which is not supported by `edflib`, sorry, see also https://www.teuniz.net/edflib/index.html.

```
Can I read/write discontinuous files?
No. Discontinuous files can be converted to continuous files with EDFbrowser.
```

The problem here as far as I see it is that the data record length is incorrectly set to `0.00` by the machine (not to mistake with the event duration, which can be 0, no problem with that)
Given the simplicity of the annotations file you could probably parse it quite easily with a simple script.

by the way, no need for a hex-viewer, the files are binary and the important parts are viewable with a regular text editor

**Comment by skjerns** [comment]
I can fully understand your frustration. The biggest problem with EDF in practice is that manufacturers do not adhere to the standard and the specifications. E.g. it is clearly defined that the time should be in format "23.30.10" not "23:30:10", however many manufacturers don't do this correctly. The creator of `edflib` takes this very serious and simply displays an error message in this case. I have to admit that I don't know whether specifying a duration of 0 is a specification violation, as far as I can see this is not the case for EDF+D.

btw as mentioned before: pyedflib and edflib are more or less the same thing, we just encapsulate the C library `edflib` and make it accesible in Python. Therefore it's also more difficult to change things if they are not working in edflib.

You can start EDFBrowser just without opening any file. Then under `tools` you find `convert EDF+D to EDF+C` - however this doesn't seem to work for this file either.

**Comment by skjerns** [comment]
Good news! I found a solution :)

The file is in fact just a EDF+C file (or compatible), but declares itself as EDF+D. If you simply ignore this and change the EDF+D to EDF+C it will load just fine in pyedflib ;-) I added a fix to ignore division by 0 errors when calculating sample rates, so install the newest release and it should work.

```Python
filename = '20201224_230408_EVE.edf'
with open(filename, 'rb') as f:    c = f.read()
with open(filename, 'wb') as f: f.write(c.replace(b'EDF+D', b'EDF+C'))

signals, sheaders, header = pyedflib.highlevel.read_edf(filename)
print(header['annotations'])
```

**Comment by bdlabitt** [comment]
Thanks so much for coming up with a solution!  Greatly appreciate it.  

I did manage to get the attention of Teunis at EDFbrowser.  He stated, "There was an issue that prevented the import of annotations from discontinuous files when
the datarecord duration was set to zero.  
I just fixed it and it seems to work now.  
The workflow is as follows:  
Open a normal (continuous) EDF+C or BDF+C file in EDFbrowser.  
Then go to Tools -> Import annotations/events and select tab "EDF+/BDF+ and click on "Import".

Just pull from Gitlab and compile from source.  
Let me know how it goes."

I'll try both solutions.  I was unaware of the above workflow, so that is helpful.  Just wanted to let you know there was a change at the edflib level as well.

Think I'll be able to make some progress today :)

**Comment by bdlabitt** [comment]
I don't know why, but the code didn't work for me.  I get a ZeroDivisionError.
Could this be as Teunis mentioned above?
`# test program for EDF+D annotation file

import pyedflib as edf
filename = '20201224_230408_EVE.edf'
with open(filename, 'rb') as f:    c = f.read()
with open(filename, 'wb') as f: f.write(c.replace(b'EDF+D', b'EDF+C'))

signals, sheaders, header = edf.highlevel.read_edf(filename)
print(header['annotations'])


# remember, when we are done to change it back!
# with open(filename, 'wb') as f: f.write(c.replace(b'EDF+C', b'EDF+D'))`
Error is:
`run testEVEedf.py
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
~/Apps/pyEDFLib/testEVEedf.py in <module>
      7 with open(filename, 'wb') as f: f.write(c.replace(b'EDF+D', b'EDF+C'))
      8 
----> 9 signals, sheaders, header = edf.highlevel.read_edf(filename)
     10 print(header['annotations'])
     11 

~/Apps/pyEDFLib/pyedf/lib/python3.8/site-packages/pyedflib/highlevel.py in read_edf(edf_file, ch_nrs, ch_names, digital, verbose)
    352         # load headers, signal information and
    353         header = f.getHeader()
--> 354         signal_headers = [f.getSignalHeaders()[c] for c in ch_nrs]
    355 
    356         # add annotations to header

~/Apps/pyEDFLib/pyedf/lib/python3.8/site-packages/pyedflib/highlevel.py in <listcomp>(.0)
    352         # load headers, signal information and
    353         header = f.getHeader()
--> 354         signal_headers = [f.getSignalHeaders()[c] for c in ch_nrs]
    355 
    356         # add annotations to header

~/Apps/pyEDFLib/pyedf/lib/python3.8/site-packages/pyedflib/edfreader.py in getSignalHeaders(self)
    130         signalHeader = []
    131         for chn in np.arange(self.signals_in_file):
--> 132             signalHeader.append(self.getSignalHeader(chn))
    133         return signalHeader
    134 

~/Apps/pyEDFLib/pyedf/lib/python3.8/site-packages/pyedflib/edfreader.py in getSignalHeader(self, chn)
    112         return {'label': self.getLabel(chn),
    113                 'dimension': self.getPhysicalDimension(chn),
--> 114                                  'sample_rate': self.getSampleFrequency(chn),
    115                 'physical_max':self.getPhysicalMaximum(chn),
    116                 'physical_min': self.getPhysicalMinimum(chn),

~/Apps/pyEDFLib/pyedf/lib/python3.8/site-packages/pyedflib/edfreader.py in getSampleFrequency(self, chn)
    389         """
    390         if 0 <= chn < self.signals_in_file:
--> 391             return round(self.samplefrequency(chn))
    392         else:
    393             return 0

pyedflib/_extensions/_pyedflib.pyx in pyedflib._extensions._pyedflib.CyEdfReader.samplefrequency()

ZeroDivisionError: float division
`
The file was changed to EDF+C and the date of the file changed.  It's ok for testing, but I don't want to give the perception of "tampering" with the data.  But pyEDFLib failed on the read of the modified file.
Please advise.

Teunis's changes for edflib worked.  Yours doesn't yet.  Do you need to rebuild pyEDFLib?

**Comment by bdlabitt** [comment]
Gee, I don't understand why python3 is getting mangled by github code enclosure.  Sorry about that.

**Comment by bdlabitt** [comment]
I see I missed your instructions to reinstall newest version.  Ooops!  Will do.

**Comment by skjerns** [comment]
Closing this issue as it is resolved(?) - feel free to open it if you still struggle with that
