### ISSUE TITLE
EDFWriter raises error when writing annotations

### ISSUE THREAD

**Issue by meta00** [holgern/pyedflib#119]
Hi, I am writing an edf file with `highlevel.write_edf` using the output of `highlevel.read_edf`. My example file is attached. The error is raised at line 736 of `edfwriter.py` for `if duration_in_seconds >= 0`: `E           TypeError: '>=' not supported between instances of 'bytes' and 'int'`.
This is because in the annotations of the header, the annotation event's `duration_in_seconds` is read as a bytes type. I tried to convert that to `float`, it worked and wrote out an edf file. This file once read in again has `duration_in_seconds` of bytes type. Could you fix either the reader or writer?
[out.edf.zip](https://github.com/holgern/pyedflib/files/6419525/out.edf.zip)

Thanks for your attention.

**Comment by skjerns** [comment]
Thanks for reporting this error.

I fixed it in #126
