### ISSUE TITLE
Option to append a channel to an existing edf file

### ISSUE THREAD

**Issue by Aaronearlerichardson** [holgern/pyedflib#128]
Is there an efficient way to append a channel to an edf file? I see there is a way to drop channels ``` pyedflib.highlevel.drop_channels() ```. What I am looking for is essentially the opposite of that. 

So far I have only had success reading the entire edf file, appending the header and channel data, and then rewriting the whole file every time. This is very slow. Is there a faster way to do this?

**Comment by skjerns** [comment]
Yes, this is the only way to do that. Drop-channels works the same way by reading the entire file and writing it again without the channels.

**Comment by Aaronearlerichardson** [comment]
In that case, is there a less memory intensive way of reading edf files than ```pyedflib.highlevel.read_edf()```? I seem to keep getting memory errors and the file is only 2 GB large.

```
>>> import pyedflib
>>> content = pyedflib.highlevel.read_edf('/home/sbf/Desktop/share/CoganLab/D_Data/Phoneme_Sequencing/D48/D48 200908 Cogan_PhonemeSequence_Session2.edf',verbose=True)
Reading Channels: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 276/276 [19:24<00:00,  4.22s/it]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sbf/anaconda3/lib/python3.7/site-packages/pyedflib/highlevel.py", line 371, in read_edf
    signals = np.array(signals, dtype=dtype)
numpy.core._exceptions.MemoryError: Unable to allocate 7.57 GiB for an array with shape (276, 3681024) and data type float64
```

I am running this on a Linux VM with ubuntu 16 and about 50 GB Memory

**Comment by skjerns** [comment]
You can try to read each channel individually (using the lower level API, not highlevel), and then reduce the data array to a `float32`, that will half the memory requirements.

Alternatively, the low level API will probably allow you to read a channel, write it directly to the output file, and then remove the channel data from memory. this way you always only load one channel at a time
