### ISSUE TITLE
CHB-MIT (Physionet) error - regular EDF not supported anymore

### ISSUE THREAD

**Issue by zaccharieramzi** [holgern/pyedflib#14]
Hi,

So I was having an issue reading some edf files from the [CHB-MIT database](https://physionet.nlm.nih.gov/pn6/chbmit/). This issue was reported [here](https://github.com/holgern/pyedflib/issues/11). I, therefore, followed your recent advice to update the `pyedflib` version.
However, I found myself with another error:
```
OSError: the file is not EDF(+) or BDF(+) compliant (it contains format errors)
```
So I looked a bit into it and here is what's happening:
in some CHB-MIT edf files (chb12_06 for example), the header contains some blacked out channels (i.e. their label is "-"). These channels have their digital maximum equal to their digital minimum. This is problematic for `pyedflib` who considers that there is a format error (that's what I understand from my poor reading of [C code](https://github.com/holgern/pyedflib/blob/master/pyedflib/_extensions/c/edflib.c#L2104)). 
This was also confirmed when I tried to open them in [EDFBrowser](http://www.teuniz.net/edfbrowser/):
```
Error, digital maximum of signal 5 is less than or equal to digital minimum
 File is not a valid EDF or BDF file.
```
I wanted to know why you had this check. What I mean is, I don't think it's really that bad if the maximum is equal to the minimum (maybe just issue a warning when they are equal) and I don't see it in the EDF specs.

I also wanted to know if others had had this issue and how they coped with it.

Don't hesitate to ask for additional details and thanks in advance for your help.

**Comment by jkuepker** [comment]
I am getting a similar error. "IOError: the file is not EDF(+) or BDF(+) compliant (it contains format errors)"

I thought it related to the number of data records in the EDF spec.
"8 ascii : number of data records (-1 if unknown)"
If I have a number of data records > 0, there are no issues, but if it is -1 for unknown then I get the error.

This is only for signals and not for annotations.  I get the error for any file with annotations.

**Comment by zaccharieramzi** [comment]
Well, maybe for that particular matter, it is because `pyedflib` chose to obey the [EDF+ spec](http://www.edfplus.info/specs/edfplus.html#additionalspecs).

However, this led me to look into this question of digital minimum, and it appears that in EDF +, the digital minimum must indeed be smaller than the digital maximum. All these checks in the C code must, therefore, mean that regular EDF is not supported anymore.

I will change the title of the question to reflect this evolution of our understanding of the issue.

**Comment by holgern** [comment]
I will change this, thank you for reporting. pyedflib should also be able to read  EDF-files.

**Comment by zaccharieramzi** [comment]
Do you know how long it will be for you to fix it? 
Because if you tell me 2 weeks I will modify my data (harmless since I can download it again) but if you think you can do it quickly, I will wait for your modifications.

Thanks for your answer.

**Comment by holgern** [comment]
Do you need a new version pushed to pypi?
I changed the source code, and chb12_06.edf can now be read by pyedflib.
Proper BDF and EDF can now be written with pyedflib

Please let me know, if there are more problems with EDF/BDF file format.

**Comment by zaccharieramzi** [comment]
Yes if it's not too much to ask, my workflow for deployment generally has `pip install -r requirements.txt`, so it would be nice if the new version was pushed to pypi.

**Comment by holgern** [comment]
Ok, i uploaded it to pypi

**Comment by zaccharieramzi** [comment]
It appears to work for me too! Thank you very much for your help :)
