### ISSUE TITLE
set_physical_minimum return value is missing

### ISSUE THREAD

**Issue by b2ag** [holgern/pyedflib#142]
It looks to me like set_physical_minimum is defined to return an integer but not actually returning the integer return by edf_set_physical_minimum. I don't know if this is by accident or not.
https://github.com/holgern/pyedflib/blob/481bdef4ad97245e875f63ecb521da0458e4e164/pyedflib/_extensions/_pyedflib.pyx#L504
Had to read the source because bad documentation. The missing return caught my attention.

**Comment by skjerns** [comment]
You are right, that was a bug, should be fixed now
