### ISSUE TITLE
"sample_frequency" is a misleading name for the number of values in a signal

### ISSUE THREAD

**Issue by gregmuellegger** [holgern/pyedflib#148]
Hi, since v0.1.23 the `getSampleFrequency` method has changed the value it returns from the actual sample rate (aka the number of samples per second) to the number of samples in the signal.

This is also documented in code. I don't know the reason why it changed but there probably was a legit reason.

Now when I used the library I stumbled upon this and tracked down the value coming from `getSampleFrequency` to this line: https://github.com/holgern/pyedflib/blob/master/pyedflib/_extensions/_pyedflib.pyx#L358 which says:
```
            return <double>self.hdr.signalparam[channel].smp_in_datarecord
```

So the actual C edflib interface calls this not sample frequency but `smp_in_datarecord`, which is a much more appropriate name IMO. I really struggled with my code and thought: Well I know I have a sample rate of 500 Hz in my data, but now the file says it is 5000 (my signals are 10 seconds), am I producing the wrong files? (sidenote, I only read BDF files with pyedflib, I'm not writing them with this lib)

This confusion IMO comes solely from the name. I'm happy to calculate the frequency (or rate or however you would like to call it) myself, but I'm 100% sure that someone else later in the code will see my calculation and say "hey there is this getSampleFrequency method provided out of the box, let's use this".

What do you think about changing the name of the attribute altogether and removing any ambiguities?

**Comment by gregmuellegger** [comment]
I just found Py-EDFLib, which seems to be doing the old calculation (e.g. seeing frequency of a number occurence per time interval): https://gitlab.com/Teuniz/EDFlib-Python/-/blob/master/src/EDFlib/edfreader.py#L509

**Comment by hojo0590** [comment]
I stumbled upon this issue as I fell for the same problem after an update to 0.1.23
I think @gregmuellegger 's point is valid. I looked it up in the official spec (which I luckily never had to bother with so far) and [there this attribute in the header](https://www.edfplus.info/specs/edf.html) is called `nr of samples in each data record` too.  
IMO `getSampleFrequency` now does not anymore do what its name advertises.

**Comment by skjerns** [comment]
This is related to #121 and #117 

I totally understand the confusion about the two terms, and I agree that it should be made clearer. In my opinion, sample frequency is colloquially understood as samples per second, and should also in pyedflib be treated as such. We need to think about how to implement this without making breaking changes again.

I think
getSampleFrequency should return sample frequencies
getSamplesPerRecord should return the "sample rate"

Additionally, these changes need to be acurately reflected when writing new files that have a record length of !=1second. I'll think about this and come up with a solution.

@holgern what are your thoughts on this?

**Comment by cleemesser** [comment]
My two cents:
In my library, I did the calculation to give the conventional use of sample frequency
```
def samplefrequency(self, channel):
        return (<double>self.hdr.signalparam[channel].smp_in_datarecord / self.hdr.datarecord_duration) * EDFLIB_TIME_DIMENSION
```

**Comment by skjerns** [comment]
@cleemesser yes, that is also how we will calculate once #159 is reviewed and merged


![image](https://user-images.githubusercontent.com/14980558/175769276-f28fc09e-8714-440a-a4ba-a9c51d2451d0.png)

**Comment by gregmuellegger** [comment]
Thank you @skjerns for taking time and effort to fix this. 👏
