### ISSUE TITLE
ValueError: numpy.ndarray size changed, may indicate binary incompatibility.

### ISSUE THREAD

**Issue by YaohuaYang** [holgern/pyedflib#156]
Env
macOS Monterey Apple M1 Pro
python 3.9.9
Numpy 1.20.3
pyedflib v0.1.24, v0.1.19

All packages we installed through 
**arch -arm64 pip install packagename==version**

Shows below error while importing pyedflib
**ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject**

Besides, I'm not able to install v0.1.20-v0.1.23 since the numpy version was limited to under 1.20.
And I don't want to upgrade NumPy over 1.20 since I have another dependency.
Can anyone help me on this issue? Thanks!

**Comment by skjerns** [comment]
have you tried the solutions from here?

https://github.com/holgern/pyedflib/issues/94

**Comment by YaohuaYang** [comment]
> have you tried the solutions from here?
> 
> #94
No, it doesn't work. Is it possible for you to compile a osx-arm64 version and upload to conda package manager? It would be supper helpful!
https://anaconda.org/conda-forge/pyedflib

**Comment by skjerns** [comment]
@YaohuaYang is this resolved by #164 ? can you try installing from master?

**Comment by YaohuaYang** [comment]
@skjerns Thanks for suggesting. I solved it with rosetta 2 + conda.
