### ISSUE TITLE
getSampleFrequencies() returns wrong sampling frequency

### ISSUE THREAD

**Issue by danjjl** [holgern/pyedflib#167]
This is a new bug.

`getSampleFrequencies()` and `getSampleFrequency()` both return a wrong sampling frequency.

E.g. I have an EDF file with channels sampled at 200 Hz, `getSampleFrequencies()` returns 20Hz.

This happens with 
- PyEDFlib : 2792a86
- Python 3.10.2
- Numpy 1.21.5

**Comment by skjerns** [comment]
Yes, this is a known issue and will be fixed in #159 , which is related to non-1 record durations

Can you try installing from that branch and see if it works then?

I'm waiting for a review by @holgern to merge the branch, then we'll create a new release with the fix.

**Comment by danjjl** [comment]
Great to hear this is already being handled.

That branch is not compatible with Numpy 1.21.5

`ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject`

This was fixed in 7cf89fb0999b9c1efa1a130be4f687925e3ac0c1

Would you maybe want to rebase the branch of a more recent commit?

**Comment by skjerns** [comment]
> Would you maybe want to rebase the branch of a more recent commit?


done!

**Comment by danjjl** [comment]
Thanks!
I can confirm #159 fixes the issue!
