### ISSUE TITLE
Error with chb17b_69 in CHB-MIT (Physionet) Database

### ISSUE THREAD

**Issue by zaccharieramzi** [holgern/pyedflib#17]
Hi,

So I was having this [issue](https://github.com/holgern/pyedflib/issues/14) on a lot of files from the [CHB-MIT db](https://physionet.nlm.nih.gov/pn6/chbmit/). Fortunately, @holgern managed to solve it. I downloaded the new version and went on with my life.

However, I hadn't noticed the error on chb17b_69 since I was focusing only on files with associated seizures:
```
OSError: the file is not EDF(+) or BDF(+) compliant (it contains format errors)
```

Unlike last time, I have no clue concerning the origin of the problem for two reasons:
- EDFBrowser hasn't solved the problem mentioned [here](https://github.com/holgern/pyedflib/issues/14); I will immediately write an issue about that. However, at the moment it's impossible for me to have additional details on why the format is bad.
- The errors in `pyedflib` are not very helpful in order to identify the origin of the bad formatting. I wonder if it's possible to enhance the errors in order to allow for "debugging".

I also compared with the file just before (chb17b_68) and the headers are the same, so it's not in that part.

Don't hesitate to ask for additional details and thanks in advance for your help.

**Comment by holgern** [comment]
The problem was that the filesize of chb17b_68 was larger than the calculated filesize. I fixed this by allowing larger filesizes.
I improved also the error messages.

**Comment by zaccharieramzi** [comment]
So cool, thank you so much.
I am waiting impatiently for the new release!

**Comment by holgern** [comment]
Yes it was  chb17b_69

**Comment by holgern** [comment]
Ok new relase 0.1.9 is online.
