### ISSUE TITLE
unused parameter 'mode' in CyEdfReader.open function

### ISSUE THREAD

**Issue by lihanhui** [holgern/pyedflib#171]
def open(self, file_name, mode='r', annotations_mode=EDFLIB_READ_ALL_ANNOTATIONS, check_file_size=EDFLIB_CHECK_FILE_SIZE):

parameter 'mode' unused!

**Comment by skjerns** [comment]
thanks, well spotted! That seems to have been a leftover/deprecated parameter. I removed it in #172
