### ISSUE TITLE
Writing to EDF affects signal values

### ISSUE THREAD

**Issue by mishashevelinn** [holgern/pyedflib#177]
I parsed an EDF file with pyedflib, modified the signal headers and saved the modified file also with pyedflib.
After comparing the resulting signals with the original, saw some minor differences between the signals. Looks like digitation noise(something with binary datatypes conversion). I found a similar issue, but it talks about using mne for processing and saving from/to different formats(I'm consistent with EDF)
See the attached plot. Units are millivolts 
![Figure_1](https://user-images.githubusercontent.com/59566253/169689420-c01ca3ba-0426-48a8-aa66-a5a4c5157efa.png)
s

**Comment by skjerns** [comment]
Have you tried loading and saving the data with `digital=True` (eg using the highlevel interface?

That should resolve the issue!

-----------
Sent from mobile

**Comment by mishashevelinn** [comment]
@skjerns , thank you for your answer! I do just renaming, but the plots taken after reading and immediate writing to examine this issue without any manipulations.
I did what you proposed, it definitely minimizes the amplitude error, it's still there but got linear in proportion to the signal amplitude itself. Any thoughts on this? Thanks again!
<img width="894" alt="image" src="https://user-images.githubusercontent.com/59566253/169900358-9daa3a62-01c7-4e5e-b0fe-b6ff82e2aa92.png">

**Comment by skjerns** [comment]
Can you post the code you are using? And maybe the signal headers of the affected signals?

**Comment by mishashevelinn** [comment]
@skjerns , you were correct, forgot to change 'analog' on writing, but changed to 'digital' on reading :)
Thanks!
