### ISSUE TITLE
The file is not edf(+) or bdf(+) compliant (sample in datarecord)

### ISSUE THREAD

**Issue by fatemehbgh** [holgern/pyedflib#193]
Hi!!
I am trying to read an EDF+C signal which raises the error above while reading it. I also install the edfBrowser and tried to use tools--header editor/repair to see the problem and actually what I can see here is that my edf signal has 3 channels which the first 2 belong to the ECG signal and the last one is the annotation and the value in the sample in data record for annotation is 0 which should be more than 0. 
there is no way to load the file to modify this value. How this issue could be fixed?

Thank you !

**Comment by skjerns** [comment]
If EdfBrowser can't load the file, there is very little we can do. We use the same underlying library `edflib`.

Best you can do is open the file in a binary text editor and try to edit the given value and see if that helps.  

Can you open the file with Edfbrowser?

**Comment by fatemehbgh** [comment]
unfortunately, I can´t even open the file with edfBrowser. I will try to open with a Binary text editor. 

Thank you!
