### ISSUE TITLE
WARNING: Sample frequencies may be incorrect!!!

### ISSUE THREAD

**Issue by NarayanSchuetz** [holgern/pyedflib#197]
Almost lost my sanity finding this.  So it turns out that newer versions of this library have a different way to calculate the sampling frequency, which may result in wrong sampling frequencies. 
Likely a result of commit 58f3e3589c7b04dac7726bb78a8f687c63f94d1e.

Now the EDF files we were using are generated by a proprietary Application, which we have no control over. The manufacturer may have messed up something that went unnoticed because they tested against the old library or maybe there are deeper issues with the current implementation.

As I'm not familiar with the reasoning behind the changes, I cannot say with certainty, but to me, this looks like a critical breaking change that should be reverted if anyhow possible as I suspect this problem may not be limited to just the Software we are using (given EDF is used as an export format with many older medical devices). 
At the very least users should be notified by a warning, because this is very difficult to debug. 

If it is wanted, I'm happy to provide a pull request with a variant where both the old and new variants to calculate the sampling frequencies are used and a warning is raised if they do not match.

Version 0.1.19:
<img width="485" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/31972290/232586108-86fcf48d-cdd0-40af-bda6-e6fb415fe25e.png">

Version 0.1.30
<img width="481" alt="Pasted Graphic 1" src="https://user-images.githubusercontent.com/31972290/232586242-00fa4deb-0251-4b20-a511-7768f06140f6.png">

**Comment by NarayanSchuetz** [comment]
Just saw this has already been reported, please at least include a warning, this is a critical bug and people should at the very least be aware!

**Comment by skjerns** [comment]
I think this is fixed in the Master version, could you check?

We are currently waiting for the owner of the repository to draft a new release @holgern , but I cannot reach him :-/

**Comment by HolgerNahrstaedt** [comment]
Sorry, I will now implement github actions for automatic package build and pypi upload.

**Comment by holgern** [comment]
Sorry, I will now work on automatic pypi upload using github actions.

**Comment by NarayanSchuetz** [comment]
@skjerns 

Yes, the Master version seems to work as expected, at least for me! Thanks for taking care of the issue.

**Comment by skjerns** [comment]
Perfekt, glad to hear! (and kind of reliefed that there is no major overseen bug in the current version)

big thanks also to @holgern for making releases more easy :)
