### ISSUE TITLE
Module doesn't work with http://www.physionet.org/pn4/eegmmidb/ dataset

### ISSUE THREAD

**Issue by shottedsheriff** [holgern/pyedflib#2]
Hi,
I have a problem using pyedflib on OS X el capitan with Anaconda 2.7. When I'm trying to open one of the subjects EDF+ file, there's this traceback:

```
---------------------------------------------------------------------------
IOError                                   Traceback (most recent call last)
<ipython-input-2-8e83f56057db> in <module>()
----> 1 f = edf.EdfReader("S001R01.edf")

_pyedflib.pyx in _pyedflib.CyEdfReader.__init__ (pyedflib/src/_pyedflib.c:2497)()

_pyedflib.pyx in _pyedflib.CyEdfReader.open (pyedflib/src/_pyedflib.c:3122)()

_pyedflib.pyx in _pyedflib.CyEdfReader.check_open_ok (pyedflib/src/_pyedflib.c:2672)()

IOError: malloc error
```

Not sure if it's related to EDFLib, pyedflib or to the dataset itself.

**Comment by plotxy** [comment]
For EEG I suggest using [mne](https://github.com/mne-tools/mne-python/).

`raw= mne.io.read_raw_edf('S001R01.edf ', preload=True, stim_channel=None)`

**Comment by plotxy** [comment]
BTW, I came looking as well, for a solution about the malloc error, which I have on Ubuntu with another type of EDF data.

**Comment by lneisenman** [comment]
I ran into a malloc error on Windows 64 with python 3.5 (see below). I tried to open the file with [EDFbrowser] (http://www.teuniz.net/edfbrowser/) which gave me an error about the file being discontinuous and suggested using a built in converter to make it continuous. That created a new file that pyedflib was able to open. 

f = pyedflib.EdfReader(filename)
File "pyedflib\src\_pyedflib.pyx", line 90, in _pyedflib.CyEdfReader.__init__ (pyedflib\src\_pyedflib.c:2672)
File "pyedflib\src\_pyedflib.pyx", line 123, in _pyedflib.CyEdfReader.open (pyedflib\src\_pyedflib.c:3285)
File "pyedflib\src\_pyedflib.pyx", line 100, in _pyedflib.CyEdfReader.check_open_ok (pyedflib\src\_pyedflib.c:2844)
OSError: malloc error

**Comment by holgern** [comment]
pyedflib depends on [edflib](http://www.teuniz.net/edflib/).
In the EDF-Files from physionet cannot be opened as the prefilter from the annotation-channel is not empty.

You can repair it with the [EDFbrowser](http://www.teuniz.net/edfbrowser/index.html).

All files, that can be opened with EDFbrowser should be opened with pyedflib.

**Comment by Paaso** [comment]
Hi!

Thanks for all your efforts with this project.

Dropped by to inform that I'm getting an identical error message.
I'm on Windows 8 64 bit, python 3.5.2 (Anaconda 4.1.1. (32-bit)).

Even when I'm trying to read the included test_generator.edf (but happens with all my .edf -files):
`test_file = 'D:/test_generator.edf'`
`if os.path.isfile(test_file) and os.access(test_file, os.R_OK): f = pyedflib.EdfReader(test_file)`
I get:
`---------------------------------------------------------------------------`
`OSError                                   Traceback (most recent call last)`
`<ipython-input-25-f9c3a9d5b173> in <module>()`
`      1 test_file = 'D:/test_generator.edf'`
`----> 2 if os.path.isfile(test_file) and os.access(test_file, os.R_OK): f = pyedflib.EdfReader(test_file)`

`_pyedflib.pyx in _pyedflib.CyEdfReader.__init__ (pyedflib\src\_pyedflib.c:2497)()`

`_pyedflib.pyx in _pyedflib.CyEdfReader.open (pyedflib\src\_pyedflib.c:3122)()`

`_pyedflib.pyx in _pyedflib.CyEdfReader.check_open_ok (pyedflib\src\_pyedflib.c:2672)()`

`OSError: malloc error`

However, all these files open with the EDFbrowser. The same error pops up, if I try to open a non-existent file.

Again, thanks for Your efforts!

**Comment by holgern** [comment]
I removed the check that prefilter or transducer have to be empty for the annotation channel.
So I close this issue
