### ISSUE TITLE
access subset of data

### ISSUE THREAD

**Issue by MitchFrankel** [holgern/pyedflib#20]
Just starting to work with EDF files for EEG.  I have some very large EDF files (10 Gb) and I only need to access a small segment of the data at a time.  I cannot find a way using this package to just extract a subset of samples using readSignal(chan).  Is this possible?  I ask because it takes a very very long time to extract all the data for 60 channels for days of data in one go.  Thank you.

**Comment by holgern** [comment]
I improved the readSignal function in the newest commit.
    def readSignal(self, chn, start=0, n=None):
        """
        Returns the physical data of signal chn. When start and n is set, a subset is returned

        Parameters
        ----------
        chn : int
            channel number
        start : int
            start pointer (default is 0)
        n : int
            length of data to read (default is None, by which the complete data of the channel are returned)

for examle f.readSignal(0,100,1000)
start and n are integer
