### ISSUE TITLE
multiple annotation channels

### ISSUE THREAD

**Issue by hkokur** [holgern/pyedflib#201]
hello, 

i am trying to write the classifications of two different technicians into one edf file and i need to write both classifications seperate annotation channels. 
is pyedflib/edfplus support the multiple annotations channel and how can i write two different classification seperate channel?

**Comment by DimitriPapadopoulos** [comment]
Does EDF+ allow multiple channels?

The EDF+ specs refer to a single annotations signal in [2.2.1. The 'EDF Annotations' signal](https://www.edfplus.info/specs/edfplus.html#annotationssignal):
> This signal is identified by giving it (in the EDF+ header) the label 'EDF Annotations'.

**Comment by DimitriPapadopoulos** [comment]
You may add a prefix to each annotation, to distinguish between technicians:
* `tech1: here is an annotation`
* `tech2: another annotation`

**Comment by skjerns** [comment]
I don't think there is a way to add a second annotation channel without violating the EDF specifications (correct me if I'm wrong!). So this can only be solved by manually using some char in front of the annotation.
