### ISSUE TITLE
gender → sex?

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [holgern/pyedflib#207]
Although _sex_ might be perceived as offensive in other contexts, in the context of life sciences it must be used instead of _gender_, where appropriate. The [EDF+ specification](https://www.edfplus.info/specs/edfplus.html#additionalspecs) is clear about it:
> \- sex (English, so F or M).

Would you agree to fix this, if backwards compatibility is assured and tested, of course?

* [What are Sex & Gender? And why do they matter in health research?](https://orwh.od.nih.gov/sex-gender)
* [What Do We Mean By Sex and Gender?](https://medicine.yale.edu/news-article/what-do-we-mean-by-sex-and-gender/)

**Comment by DimitriPapadopoulos** [comment]
See:
https://gitlab.com/Teuniz/EDFlib/-/issues/12S

**Comment by skjerns** [comment]
if this is implemented in upstream `edflib`, surely we'll change this as well.

**Comment by skjerns** [comment]
Proposal: Change all functions to use "sex" instead of "gender", but keep previous functions with DeprecationWarning.

**Comment by DimitriPapadopoulos** [comment]
I could copy the latest versions of `edflib.h` and `edflib.h` from EDFlib, but I understand you have slightly modified them. What would you suggest?

**Comment by skjerns** [comment]
> I could copy the latest versions of `edflib.h` and `edflib.h` from EDFlib, but I understand you have slightly modified them. What would you suggest?

indeed, there are some modifications which make it hard to simply update. For now we could either only adapt it in the python code or additionally integrate the changes in the C files into the current code base. 

It's a bit unfortunate that the C files are altered so much. Maybe in the future we should think about keeping the original C/h files in our code base and only do alterations in the Python files, or as additional C files

**Comment by DimitriPapadopoulos** [comment]
We can keep the C files as they are for now. They are not visible by end users.
