### ISSUE TITLE
Cannot open file containing accented character on Windows

### ISSUE THREAD

**Issue by rafaelgm** [holgern/pyedflib#21]
Hi,

First, thanks for this great library! :)

If I try to open a file containing an accented character on it's name, on Windows (like "á"), I get an error (see below). If the accented character is removed from the file name, the file opens normally.

Stack trace:

```
OSError                                   Traceback (most recent call last)
    126 
--> 127     with pyedflib.EdfReader(filename) as f:
    128         print(f.signals_in_file)
    129 

pyedflib\_extensions\_pyedflib.pyx in pyedflib._extensions._pyedflib.CyEdfReader.__init__()

pyedflib\_extensions\_pyedflib.pyx in pyedflib._extensions._pyedflib.CyEdfReader.open()

pyedflib\_extensions\_pyedflib.pyx in pyedflib._extensions._pyedflib.CyEdfReader.check_open_ok()

OSError: can not open file, no such file or directory
```

**Comment by holgern** [comment]
Thanks for reporting.
The problem should be fixed now.
I will push a new release 0.1.11

**Comment by skjerns** [comment]
I've reverted the change, as it recently seemed to cause problems again that I could fix by reverting to UTF8 encoding. See #77 .

Hope everything works, if not let me know, then I'll revert the revert  ;-)
