### ISSUE TITLE
Annotations get truncated to 40 characters

### ISSUE THREAD

**Issue by arjunmgh** [holgern/pyedflib#215]
when i write annotations using-
f.writeAnnotation(onset_time, duration, event_type)

where event_type is the annotation,
the annotations are truncated to 40 characters, is there a limit to the length of a single annotation?

**Comment by skjerns** [comment]
Upon inspection I found that in the original `edflib`, the maximum annotation length (`EDFLIB_WRITE_MAX_ANNOTATION_LEN`) is set to 40. However, in the specifications I cannot find a reason why this should be the case.

I have raised the issue [here](https://gitlab.com/Teuniz/EDFlib/-/issues/13) and will report back.

**Comment by skjerns** [comment]
It's "on the wishlist", so might be included in the next release. For now, you either need to limit yourself to 40 chars or compile `pyedflib` yourself while setting `EDFLIB_WRITE_MAX_ANNOTATION_LEN` to a higher value in developer mode.

**Comment by arjunmgh** [comment]
Thank you for your help!
