### ISSUE TITLE
Incompatible with numpy>=1.25

### ISSUE THREAD

**Issue by wenh06** [holgern/pyedflib#218]
Numpy released version 1.25 a few days ago, and `Tester` is removed from this version, ref. [NumPy 1.25.0 Release Notes](https://github.com/numpy/numpy/releases/tag/v1.25.0).

>>> File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/pyedflib/__init__.py", line 19, in <module>
>>> from numpy.testing import Tester
>>> ImportError: cannot import name 'Tester' from 'numpy.testing' 

Perhaps, the requirements should be updated to restrict to `numpy < 1.25` or remove the usage of `Tester` in the [`__init__.py` file](https://github.com/holgern/pyedflib/blob/master/pyedflib/__init__.py).

**Comment by wenh06** [comment]
There's already PR #216

**Comment by skjerns** [comment]
should be fixed in #216

**Comment by wenh06** [comment]
Uploading to PyPI [failed](https://github.com/holgern/pyedflib/actions/runs/5362811169/jobs/9730443796), since the minor version number is not changed, which should be incremented by one, as in #227
