### ISSUE TITLE
setup.py → pyproject.toml

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [holgern/pyedflib#225]
Move to `pyproject.toml` and make `setup.py` a thin wrapper

[Configuring setuptools using `pyproject.toml` files](https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html)

**Comment by skjerns** [comment]
This would probably be a bit hacky due to the Cython compilation and Numpy Extension stuff. See e.g. https://stackoverflow.com/questions/73800736/pyproject-toml-and-cython-extension-module

Unless there is an advantage or `setup.py` get's deprecated I'd prefer to leave it as is.

**Comment by DimitriPapadopoulos** [comment]
Indeed `setup.py` is slowly getting deprecated. See for example https://github.com/adrienverge/yamllint/issues/509#issuecomment-1493351047.
