### ISSUE TITLE
`readsignal` fails to retrieve data

### ISSUE THREAD

**Issue by rr1017** [holgern/pyedflib#228]
The function fails to retrieve data with the following error: 
```
read -1, less than 921600 requested!!!
```
The edf file for which this happens is readily available from physionet.org (chb01_01.edf)

**Comment by DimitriPapadopoulos** [comment]
Are you certain the file is an error-free EDF file?

Please provide a link to a compliant EDF file.

**Comment by DimitriPapadopoulos** [comment]
Found a `chb01_01.edf` file in the [CHB-MIT Scalp EEG Database](https://physionet.org/content/chbmit/1.0.0/).

**Comment by DimitriPapadopoulos** [comment]
This works for me:
```python
import pyedflib

signals, signal_headers, header = pyedflib.highlevel.read_edf("chb01_01.edf")
```

How to reproduce the error?

**Comment by rr1017** [comment]
That was the file I was using, I see pyedflib.highlevel.read_edf works but I just wonder why readSignal on the EdfReader class won’t work.

So, if I create an instance of EdfReader with that file and I try to use the readSignal(chn=1) method it fails.

I have switched to using the “mne” library anyway which has similar functionalities but I would recommend attempting to solve this issue.

Best regards,

Ruben Ruiz-Mateos Serrano
MRes+PhD Connected Electronic and Photonic Systems
Department of Engineering
University of Cambridge / UCL

**Comment by skjerns** [comment]
I cannot reproduce the issuse, I assume the problem is with your code.

```Python
import pyedflib
file_name = '/home/simon/Downloads/chb01_01.edf'
with pyedflib.EdfReader('chb01_01.edf') as f:
    n = f.signals_in_file
    signal_labels = f.getSignalLabels()
    print(n, signal_labels)
    f.readSignal(1)
```
