### ISSUE TITLE
Issues reading EDF's

### ISSUE THREAD

**Issue by gadallon1** [holgern/pyedflib#24]
When I am trying to use the code on NSSR dataset, I am getting the following error message: 
ValueError: could not broadcast input array from shape (3483750) into shape (27870)
when running 
sigbufs[i, :] = f.readSignal(i)

**Comment by davidhsmith** [comment]
This happened to me to.  It seems to not be an issue with pyedflib but with the demo code which assumes all the signals are same length.  The NSRR datasets don't satisfy this.   Try the following alternative to the demo code:

```python
>>> import pyedflib
>>> import numpy as np
>>> f = pyedflib.EdfReader(r"C:\Users\davids\Downloads\shhs2-200078.edf")
>>> n = f.signals_in_file
>>> signal_labels = f.getSignalLabels()
>>> sigbufs = [np.zeros(f.getNSamples()[i]) for i in np.arange(n)]
>>> for i in np.arange(n):
>>>     sigbufs[i] = f.readSignal(i)
```

**Comment by holgern** [comment]
I improved the demo 
Thanks for reporting.
