### ISSUE TITLE
filename, ids and names when read by neuroscore

### ISSUE THREAD

**Issue by sronilsson** [holgern/pyedflib#249]
Thanks for a great tool, I use it to convert data to edf format for reading in DSI NeuroScore. All goes well except filename on the main header is named X, and in the library the “ID” and “Name” are also x which I presume is some placeholder default. Can you point me to where I set this parameter in edf file?

many thanks! 

<img width="910" alt="image" src="https://github.com/holgern/pyedflib/assets/34761092/367407ee-9b2c-4264-b258-c364d2340f1c">

**Comment by skjerns** [comment]
How do you create the files?

You can set these fields in the header

**Comment by sronilsson** [comment]
Thanks @skjerns, I initialize file with:

```
f = pyedflib.EdfWriter(file_name=file_name,
                       n_channels=len(channel_names),
                       file_type=pyedflib.FILETYPE_EDF)
```

And set headers with:

```
for i in range(len(channel_names)):
    f.setSignalHeader(i, channel_info={'label': channel_names[i],
                                       'dimension': 'mV',
                                       'sample_frequency': sample_rates[i],
                                       'physical_min': physical_min[i],
                                       'physical_max': physical_max[i],
                                       'digital_min': digital_min[i],
                                       'digital_max': digital_max[i]})
```

which arguments sets these names? Cheers!
