### ISSUE TITLE
conda release outdated (1.32 from 04/2023)

### ISSUE THREAD

**Issue by hojo0590** [holgern/pyedflib#250]
Your [README also explains under installation](https://github.com/holgern/pyedflib#installation) how `pyedflib` can be installed with conda, yet the version [available on conda-forge](https://anaconda.org/conda-forge/pyedflib/files) is quite old and lacking the newest improvements and fixes.  
Any chance on fixing the issues with https://github.com/conda-forge/pyedflib-feedstock so your most recent releases will be available on conda again?

**Comment by skjerns** [comment]
as far as i can see, only @holgern can do that, is that correct?

**Comment by hofaflo** [comment]
You might be able to add yourself as a maintainer, see [here](https://conda-forge.org/docs/maintainer/updating_pkgs.html#updating-the-maintainer-list)

**Comment by skjerns** [comment]
Nice, that seemed to have worked :)

https://github.com/conda-forge/pyedflib-feedstock/issues/36

Do you have experience with conda feedstock and can point me to what I need to do next?

**Comment by skjerns** [comment]
I think it should be fixed now, at least according to https://anaconda.org/conda-forge/pyedflib

Can you check @hofaflo ?

**Comment by hofaflo** [comment]
Just tested with Miniconda and Python 3.12.2, seems to work :)
