### ISSUE TITLE
Annotation start time overflow

### ISSUE THREAD

**Issue by MitchFrankel** [holgern/pyedflib#255]
Using pyedflib 0.1.17. In EdfWriter.writeAnnotation, it uses np.round(onset_in_seconds*10000).astype(int).   This only allows for onset_in_seconds up to 4.97 days before it overflows int, which is really int32, and bonks. If the data is longer than 4.97 days, and there are annotations that need to go there, how can one write annotations that won't overflow?

**Comment by skjerns** [comment]
Is there a reason you need to use `v0.1.17`? newest version is `v0.1.37`

This has been changed to `int64` in https://github.com/holgern/pyedflib/pull/176 , so `pyedflib>=v0.1.31` supports it
