### ISSUE TITLE
ERROR reading edf file: the file is not EDF(+) or BDF(+) compliant (Digital Maximum)

### ISSUE THREAD

**Issue by hannekevandijk** [holgern/pyedflib#26]
Hi,

I am trying to read .edf files, and get this error for some of them....it might be older files. I have upgraded to the last version of pyedflib (0.1.10).

Could you help me? What information do you need from me?

Best Hanneke

**Comment by holgern** [comment]
Hello,
can you give me an edf-file that has this kind of error?

Best regards,
Holger

**Comment by hannekevandijk** [comment]
Hi Holger,

It really seems to depend on my datasets, sorry, I tried to open them in Matlab as well and they give the same warning. I have to ask whether I can give the data, as they are clinical datasets. If you are still interested I will see what I can do.

Best regards,

Hanneke

**Comment by holgern** [comment]
Thank you, I'm still interested.

**Comment by Shuvrajit9904** [comment]
Has there been any progress on this? I am facing the same issue.

**Comment by danzhewuju** [comment]
you need convert EDF+D to EDF+C.

**Comment by hannekevandijk** [comment]
How do you do that?

**Comment by hannekevandijk** [comment]
> Hello,
> can you give me an edf-file that has this kind of error?
> 
> Best regards,
> Holger

Can I do that privately? It is a file that might contain AVG sensitive data, which I am not sure of since I cannot open it...

**Comment by hannekevandijk** [comment]
![afbeelding](https://user-images.githubusercontent.com/29751082/84788370-5a954d00-afef-11ea-81af-77809e88b41f.png)

If I have a look at the file with edfbrowser (Teunis van Beelen) than it gives this error. While Brain Vision Analyser doesn't have any problems with it...

Sorry for the long silence, I have been working with other data in the mean time

**Comment by skjerns** [comment]
The digital maximum (ADC values) of EDF is 32767 (INT16), however it should be possible with BDF, which extends it to 8388607 (INT4). Which device/software created this file?

Have you tried the Header-Repair-Tool by EDFBrowser?

(EDFBrowser -> Tools -> Header Editor -> Open your file, and save it again)

You can send the file to k08mqyp8efg@temp.mailbox.org and I'll have a look. Just drop me a dropbox or wetransfer link :)

PS: Groeten naar Nijmegen!
