### ISSUE TITLE
Add Type Hints for Improved Static Analysis

### ISSUE THREAD

**Issue by joseph-pq** [holgern/pyedflib#263]
Hi! I noticed that the codebase currently lacks type hints. I'm wondering if this was an intentional decision or if it's a TODO item for the project.

Type hints would bring several benefits, such as:

- Improved code readability and maintainability.
- Better support for IDEs and developer tools that rely on static type checking.
- Potential to integrate with static analysis tools like mypy to catch type-related issues earlier in the development process.

Would you be open to introducing type hints throughout the project? If so, I'd be happy to help by submitting a pull request or working with the team to add them.

Looking forward to your thoughts!

**Comment by skjerns** [comment]
Good idea! There's no reason not to do that :)

If you want to go ahead, feel free to make a PR!
