### ISSUE TITLE
ValueError: could not broadcast input array from shape (1205) into shape (301250)

### ISSUE THREAD

**Issue by rushikeshsp25** [holgern/pyedflib#32]
I am trying to read edf file but getting an error as:->  ValueError: could not broadcast input array from shape (1205) into shape (301250).

**Comment by m-granat** [comment]
Same thing!

**Comment by alokm014** [comment]
I think u have to try my code [link](https://github.com/alokm014/sleep-dataset-extraction/blob/master/edf_to_csv.py)

**Comment by skjerns** [comment]
This is probably due to the sampling frequencies of the channels being different.

You can circumvent this by using the highlevel API or loading each channel individually:

```Python
import pyedflib
signals, signal_headers, header = pyedflib.highlevel.read_edf(file)

# or alternatively loading individually
with pyedflib.EdfReader(edf_file) as f:
    n_chrs = f.signals_in_file
    for i,c in enumerate(ch_nrs):
        signal = f.readSignal(c, digital=digital)
        signals.append(signal)
```

Hope this solves your problem. If not, please supply a sample file and the code you are using for loading.
