### ISSUE TITLE
pyedflib.EdfReader() fails on non-compliant EDFs

### ISSUE THREAD

**Issue by DMRoberts** [holgern/pyedflib#36]
For several EDFs, for example [n12.edf](https://www.physionet.org/physiobank/database/capslpdb/n12.edf), [n13.edf](https://www.physionet.org/physiobank/database/capslpdb/n13.edf), and [n14.edf](https://www.physionet.org/physiobank/database/capslpdb/n14.edf) available from the PhysioNet CAP data set (https://www.physionet.org/physiobank/database/capslpdb/) pyedflib.EdfReader() fails to load the file, noting that "OSError: the file is not EDF(+) or BDF(+) compliant". Would it be possible to have the option to skip the non-compliant header information, so the incorrect header data could be fixed post-hoc by the user?

**Comment by alokm014** [comment]
I think my code will solve your problem just have a look: [link](https://github.com/alokm014/sleep-dataset-extraction/blob/master/edf_to_csv.py)

**Comment by DMRoberts** [comment]
Thanks for the suggestion, that script wouldn't resolve the issue with those files, however, since it uses pyedflib.EdfReader to read, which fails.

**Comment by skjerns** [comment]
We rely on the C library `edflib` to load files. If the library cannot open a file, `pyedflib` also cannot load it in most cases. We would need to edit the C library to make that work, which we try to avoid.

Rule of thumb: If [EDFBrowser](https://www.teuniz.net/edfbrowser/) cannot load a file, we also cannot.
