### ISSUE TITLE
readSignal error: read -1, less than 921600 requested!!!

### ISSUE THREAD

**Issue by ShireLiuSZ** [holgern/pyedflib#45]
when I read chbmit01_03.edf file, 
`       f   = pyedflib.EdfReader(fname)
        nSignals      = f.signals_in_file  
        nSamples      = f.getNSamples()[0]  #it is 921600
        signal_labels = f.getSignalLabels() 
        freq          = f.getSampleFrequency(0)
        t             = np.arange(nSamples, dtype=float)/60.0/freq 
        eeg       = np.zeros((nSignals, f.getNSamples()[0]))

        for i in range(nSignals):
            print(f.readSignal(i).shape)
            eeg[i, :] = f.readSignal(i)`
I cann't read the data into eeg, it shows "read -1, less than 921600 requested!!!", how to deal with it？ Thank you very much!!

**Comment by s151202** [comment]
Hi ShireLiuSZ, I have the same error when I was reading an imported .edf file. Have you found any solutions?

Thanks,
James

**Comment by ShireLiuSZ** [comment]
Hi James, 
[https://stackoverflow.com/questions/46431900/pyedflib-error-reading-signal](url)
 this answer may help you~
