### ISSUE TITLE
Re-writing EDF file changes signal data and signal header values

### ISSUE THREAD

**Issue by eniemela3** [holgern/pyedflib#46]
I'm reading an EDF file with EdfReader and I received the following signal headers and data values (excerpt):
...        
"physical_max": 5859.19,
"physical_min": -5859.3,
"digital_max": 32767,
"digital_min": -32768,
...
... , 926.99941985, 875.32255085, 830.26175158, ...

The min and max values in the data were
5859.19
-5859.300000000001

I re-wrote the file using EdfWriter and when reading the result I received the following signal headers and data values:
...
"physical_max": 5859.189,
"physical_min": -5859.3,
"digital_max": 32767,
"digital_min": -32768,
...
... ,926.99884074, 875.32197615, 830.26118073, ...

The min and max values were
5859.189
-5859.300000000002

Why does EdfWriter shift the values down? Also, why is the physical_min value exceeded?

The scaling offset computed via the max values (e.g. here https://github.com/holgern/pyedflib/blob/master/pyedflib/_extensions/c/edflib.c#L4911) does not correspond to the EDF software guidelines: the scaling should be done via minimum values, as in "the formula to compute the physical value, P, from the digitally stored (16-bit integer) value, D, reads: P = Pmin   +  (Pmax - Pmin) * (D - Dmin) / (Dmax - Dmin)" (see https://www.edfplus.info/specs/guidelines.html). Could this be the source of this error?

**Comment by skjerns** [comment]
I think this is a very important issue.

I also see that reading and writing the file changes values within. I always shrugged it off as rounding errors, but some of them seem to be too large to accept. If I have time I'll dig deeper into this

**Comment by skjerns** [comment]
This is due to rounding errors that get introduced by converting forth and back from digital to analog signal space. EDF saves files in digital space (i.e. amplifier integers), and then converts to floats (i.e. Voltage) as output, depending on the digital range dmin/dmax, there can be loss of information.

Try loading and saving the data with digital=True, the signal should then stay the same

**Comment by aarongerston** [comment]
I am reading and writing with digital=True, and still physical_max and physical_min values are being altered (from 12582.91 to 12582.9 and -12582.9 to -12582.8, respectively). This is, of course, affecting the signal data as well.

Note that other signals in my data set with pmin and pmax values of -12.5829 and 12.58291 are not changed.

**Comment by skjerns** [comment]
That's strange - do you have a sample file and code for me to check? 

(if you can't share the file publicly, you can upload it here: https://cloud.skjerns.de/index.php/s/Zc23WTPbMrMBkK3)

**Comment by aarongerston** [comment]
Thanks for the quick response. I've uploaded a test EDF file as well as a Python test script that demonstrates the problem and outputs the inconsistencies observed. For reference, I'm running with the following specs:

pyedflib=0.1.36
numpy=1.26.3
Python=3.9.13
OS=Windows 11 Pro

Let me know if more information would be helpful.

**Comment by skjerns** [comment]
I think there is a rounding error in `edflib`

https://github.com/holgern/pyedflib/blob/3bbcdc03396cf88d3bc73b276e65acf55fac520a/pyedflib/_extensions/c/edflib.c#L5725

As input, the function gets 
```
    printf("My pre value is: %f\n", hdr->edfparam[i].phys_max);
    p = edflib_snprint_number_nonlocalized(str, hdr->edfparam[i].phys_max, 128);
    printf("My post value is: %s\n", str);

# My pre value is: 12582,910000
# My post value is: 12582.909999999
```

There seems to be a rounding error when converting from double to string. Not sure if that's soley on `edflib`s side, I'll check.

**Comment by skjerns** [comment]
I applied the patch created by Teuniz which adds a small offset to circumvent truncation. New version should be out soon.

**Comment by aarongerston** [comment]
Fantastic! (And impressively expedient!)
Please update when released, if you can. 

Many thanks!

**Comment by skjerns** [comment]
Release is out

**Comment by skjerns** [comment]
whoops, might need to revert, patch has been retracted: https://gitlab.com/Teuniz/EDFlib/-/issues/15#note_1816944048
