### ISSUE TITLE
edf writer code executing really slow

### ISSUE THREAD

**Issue by abhishekupadhyaya** [holgern/pyedflib#5]
Hi,

I am trying to create a edf file combining the small chunks of signals from the original edf file. There are 129 signals each with 2 hours long of data and each having sample frequency of 2000Hz. I have been trying to combine all 129 signals for last couple of days but I am not able to complete the process even when running the machine for 8 hours. However, I am able to combine upto 18 signals and even then it takes really long time.

I used the demo code for edfwriter and modified based on my need using a loop to add signals to data_list.

Could you let me know how I could write edf file faster?

Thank you

**Comment by holgern** [comment]
Hi,
can you try again? I changed the code for edfwriter and use now blockwrite. It should now work faster with several channels. Your python code remains the same, just update the pyedflib-code and compile and install it again.

**Comment by abhishekupadhyaya** [comment]
I tried it again.

To update the pyedflib-code, can I just do pip install --upgrade? When I did that I get the message "Requirement already up-to-date:". However, even then the execution is still slow.

**Comment by holgern** [comment]
I released now 0.1.5 with the changes and uploaded it to pypi. Thus pip install --upgrade should work now. Can you try again?

**Comment by abhishekupadhyaya** [comment]
I tried the updated version. It still didn't work faster. I just tried 6 channels with the same duration of data and sample frequency. It took me 32 minutes to write a edf file. I am not sure what I am doing wrong here.

**Comment by holgern** [comment]
Can you give me your script and sample data? Then I can test and fix.

**Comment by abhishekupadhyaya** [comment]
thank you!

I have attached a zip file with script and chunk files for 13 channels. the chunk files in the script are smaller than the ones that I am currently using but i have tried to make the array for each channel the same size as the one that i am using at my work by looping through appending the same array 20 times.

each channel array should be have length of 14400000. this is to make it similar to my actual data set that i am working with.

you just have to run script.py and it should read the chunk files and create a edf file in the same directory.

thank you again!

[test-folder.zip](https://github.com/holgern/pyedflib/files/516355/test-folder.zip)

**Comment by abhishekupadhyaya** [comment]
were you able to test with sample data?

**Comment by holgern** [comment]
yes, and I think I found the problem. I trying to fix it right now.

**Comment by holgern** [comment]
Ok, I found the problem. Can you try again with the newest version 0.1.6?

**Comment by holgern** [comment]
Can I add your example code with the test data to the demos of pyedflib?

**Comment by abhishekupadhyaya** [comment]
I will try the new version and let you know how it works with my data.
Yes you can use my example code and test data. Thank you for fixing the problem.
