### ISSUE TITLE
Cannot create and open file containing non standard ASCII characters on Windows

### ISSUE THREAD

**Issue by yurasmol** [holgern/pyedflib#52]
pyedflib.EdfReader and pyedflib.EdfWriter can not operate with extended ASCII symbols (CP1251).
"can not openfile, no such file or directory

[TEST.zip](https://github.com/holgern/pyedflib/files/3024946/TEST.zip)

"

**Comment by skjerns** [comment]
I cannot reproduce the problem as it loads just fine for me:

```Python
from pyedflib import highlevel
file = './ÅÉÄüÇ.edf'
signal, signal_headers, header= highlevel.read_edf(file)
```

Are you using Python 3.X with UTF-8 encoding?

@yurasmol  try opening the file with Python `open`:
```Python
file = './ÅÉÄüÇ.edf'
with open(file, 'rb') as f:
    c = f.read()
```

If this also doesn't work then the problem isn't on our side.
