### ISSUE TITLE
writing digital sample data is not available.

### ISSUE THREAD

**Issue by anwarhamr** [holgern/pyedflib#6]
Updating comment.  I have successfully added the write_digital_signal code but found out that we are not handling errors from the c library.  
I don't get an error when I write a signal header with matching physicalmin and max values.  The file is created, the file handle is never released and no error is raised.  
I'm going to do a pull request in the next day for my changes for write digital and may make time to look into error/exception handling after that.  
Thanks for the library!

**Comment by skjerns** [comment]
Is there any update in this?

I'm trying to write my digitial signals to an EDF file, but with no success.
