### ISSUE TITLE
Incorrect header leads to modified signal

### ISSUE THREAD

**Issue by HKH515** [holgern/pyedflib#61]
I noticed that when reading a signal with EdfReader, and writing it back out with all the fields the same (all headers, all signals, are unchanged) using EdfWriter, some channels might have its output "clipped"; this seems to happen when the digital values in the signal exceed the range of the digital max/min header for that signal. This is something that, in my opinion, should not be happening, as the output file should be written exactly as the input file (identity mapping).

One thing to mention here is that edf files from research labs, physionet, and other sources sometimes have incorrect digital max/min header values, but the data is still of value to researchers, who would like to use the "unclipped" data, either for validation of findings or for original research.

It seems as the following code section is the culprit, from quick inspection.

```c
if(value>digmax)
{
  value = digmax;
}

if(value<digmin)
{
  value = digmin;
}
```
This is found in edflib.c, at lines 
4001-4009,
4125-4133,
4255-4263,
4386-4394,
4617-4625,
4772-4780

**Comment by skjerns** [comment]
It's due to the underlying `edflib`.

I've [posted the issue](https://gitlab.com/Teuniz/EDFlib/issues/3#note_299676621) on your behave there, and as I expected it will not be implemented, as it would be a violation of the EDF standard

**Comment by HKH515** [comment]
Oh well, thanks for the answer!
