### ISSUE TITLE
request to provide a sample script to de-identify edf

### ISSUE THREAD

**Issue by catvasily** [holgern/pyedflib#64]
Thank you for sharing the package.
May I kindly ask you to provide a sample script on how to remove patient's name from a given EDF+, or to replace it with a fake name.
Thank you.

**Comment by skjerns** [comment]
I have something like that written. I'll upload it for you, but it requires a few more scripts and functions as well. I'll see if I can make a PR with some more high-level functions to this package.

**Comment by skjerns** [comment]
@catvasily 

I've added the functions and created a PR #65 .

Until then you can find the functions here: https://github.com/skjerns/pyedflib

more specifically: https://github.com/skjerns/pyedflib/blob/master/pyedflib/highlevel.py

**Comment by catvasily** [comment]
Thank you @skjerns ! It was helpful!
My original EDF files contain annotations, and after anonymization, they are gone.
Is there a way to keep annotations?

**Comment by skjerns** [comment]
Ahh, right, I totally forgot that those exist.

I'll see if I'll find time today to adapt the script.

**Comment by skjerns** [comment]
@catvasily try again, should work now :)

**Comment by catvasily** [comment]
Thank you @skjerns for refining your toolbox!
The annotations are there! The only thing is that their exact timing in the anonymized edf is rounded to seconds, so in general, the annotations are shifted, up to 1 second.

**Comment by skjerns** [comment]
Mhh, yes, unfortunately that's a problem with the code of `EDFWriter` itself. I can check if I can alter this.

**Comment by skjerns** [comment]
@catvasily ? does it work for you?

**Comment by catvasily** [comment]
Thank you @skjerns for improving your toolbox.

The annotations are still rounded up to 1 second.

By the way, the last line in the sample script demonstrating "Highlevel Interface" on https://pypi.org/project/pyEDFlib/, should be highlevel.anonymize_edf('edf_file.edf'), right?

**Comment by skjerns** [comment]
did you install the develop version?

`pip install git+https://github.com/holgern/pyedflib.git`

**Comment by catvasily** [comment]
Failed to build pyedflib 
I use Anaconda environment 3.7, and am getting an error:
ERROR: Could not build wheels for PeEDFlib which use PEP 517 
I tried to use
> pip install --upgrade pip setuptools wheel
but at no avail.
Any suggestions? 
Thank you.

**Comment by skjerns** [comment]
You need to install an VS C++ compiler, e.g. this one [Microsoft Visual C++ Compiler for Python 2.7](https://www.microsoft.com/en-us/download/details.aspx?id=44266) and make sure the compiler exe (`cl.exe`).

**Comment by catvasily** [comment]
Thank you @skjerns !
I was able to successfully build pyedflib (by installing the python compiler and fixing some issues with Studio 2019).
highlevel.anonymize_edf() introduces one small change though:
it rounds the start time up to 1 second.
For example, for the original edf: start time = 5 sep 2017  10:33:33.4628906
but for the new (de-identified) edf: 5 sep 2017  10:33:33
so it shifts the timing of all the annotations accordingly.
I am wondering if there a way to fix it? Thanks.

**Comment by skjerns** [comment]
Unfortunately, `EDF` only allows the starttime to be set to seconds, not milliseconds, see https://www.edfplus.info/specs/edf.html 

> 8 ascii : starttime of recording (hh.mm.ss)

**Comment by catvasily** [comment]
Now I am surprised myself.
It is a clinical EEG converted from Natus's proprietary format.
Would be happy if you can take a look.
Can we switch to email correspondence please.

**Comment by catvasily** [comment]
0       X F 24-SEP-1996 Lastname,Firstname                                                Startdate 05-SEP-2017 X X X                                                     05.09.1710.33.339216    EDF+C                                       1347    1       35  Trigger Event   Patient Event   C3              C4              CZ              F3              F4              F7              F8              FZ              FP1             FP2             FPZ             O1              O2              P3              P4              PZ              T3              T4              T5              T6              AUX1            ECG1            ECG2            AUX4            AUX5            AUX6            AUX7            AUX8            PG1             PG2             A1              A2              EDF Annotations                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 uV      uV      uV      uV      uV      uV      uV      uV      uV      uV      uV      uV      uV      uV      uV      uV      uV      uV      uV      uV      uV      uV      uV      uV      uV      uV      uV      uV      uV      uV      uV      uV              0       0       8711    8711    8711    8711    8711    8711    8711    8711    8711    8711    8711    8711    8711    8711    8711    8711    8711    8711    8711    8711    8711    8711    8711    8711    8711    8711    8711    8711    8711    8711    8711    8711    -1      1       1       -8711   -8711   -8711   -8711   -8711   -8711   -8711   -8711   -8711   -8711   -8711   -8711   -8711   -8711   -8711   -8711   -8711   -8711   -8711   -8711   -8711   -8711   -8711   -8711   -8711   -8711   -8711   -8711   -8711   -8711   -8711   -8711   1       0       0       -32768  -32768  -32768  -32768  -32768  -32768  -32768  -32768  -32768  -32768  -32768  -32768  -32768  -32768  -32768  -32768  -32768  -32768  -32768  -32768  -32768  -32768  -32768  -32768  -32768  -32768  -32768  -32768  -32768  -32768  -32768  -32768  -32768  1       1       32767   32767   32767   32767   32767   32767   32767   32767   32767   32767   32767   32767   32767   32767   32767   32767   32767   32767   32767   32767   32767   32767   32767   32767   32767   32767   32767   32767   32767   32767   32767   32767   32767                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   512     512     512     512     512     512     512     512     512     512     512     512     512     512     512     512     512     512     512     512     512     512     512     512     512     512     512     512     512     512     512     512     512     512     184

**Comment by skjerns** [comment]
leave me a message at dktll0vdezb@temp.mailbox.org

**Comment by skjerns** [comment]
`05.09.1710.33.339216`
`dd.mm.yyhh.mm.ss` + 8 bytes header lengths.

Your recording also starts at a second mark

**Comment by skjerns** [comment]
It seems that the information is not annotated in the header itself, but rather inside the signal blocks, must be something by EDF+C/D I'm not aware of. However, I cannot figure out yet how to access this information, as it's not part of the header itself.

`pyEDFlib` is a wrapper for a library written in C called `EDFlib`. `EDFBrowser` is also based on `EDFlib`. So theoretically `EDFlib` should be able to read this offset information, probably named there `starttime_subsecond`. However, I can't seem to be able to read this information with our wrapper. I'll ask the creator of `EDFlib` for assistance.

**Comment by Teuniz** [comment]
There were two problems with EDFlib:  

1. When opening a file for reading, a bug caused the subsecond starttime to be always zero.  

2. There was no function to write the subsecond starttime when writing a new file.  

Both issues have been addressed in EDFlib.  

Kind regards,

Teunis

**Comment by skjerns** [comment]
@Teuniz Thank's for the quick response! That's great news. I'll move this to #79 and implement the changes from there, and report back here once I'm done.

**Comment by skjerns** [comment]
@catvasily I've implemented the changes for subsecond accuracy. Can you check if it works?

Test it with the dev version: pip install git+https://github.com/holgern/pyedflib.git

**Comment by catvasily** [comment]
Hi @skjerns, it is working!!
The timing is preserved now, and 
max(original_signal_amplitudes - anonimyzed_signal_amplitudes) = 0, as expected.
I have noticed a very small difference in the time stamps for annotations - it is of the order of 10^(-4) second. 
For example,
for one annotation in the original edf: 0:09:25:3905, 
but for the corresponding annotation in the anonymized edf: 0:09:25:3906,
which is not critical.
The rest seems to be the same.
Thank you for developing this toolbox.  It is really helpful!

**Comment by skjerns** [comment]
@catvasily that's great to hear.

I'll look into the issue with the shift by 0.1ms. It really isn't much, however it would still be better to have it consistent.

**Comment by skjerns** [comment]
@catvasily can you install the latest master version and try again? I've fixed some small thing when converting.

**Comment by skjerns** [comment]
this seems to be  a problem with writing the annotations, not with the starttime itself. The starttime is set accurately, but the annotations not. I'll continue here #86
