### ISSUE TITLE
Numpy dependency

### ISSUE THREAD

**Issue by MeNsaaH** [holgern/pyedflib#72]
Instead of failing on installation if numpy is not found, it'll be better to add it to setup.py `install_requires`

**Comment by skjerns** [comment]
I'm quite surprised, because numpy is in the requirements: 

`install_requires=["numpy>=1.9.1"]`

https://github.com/holgern/pyedflib/blob/0fd2c3e9c164c2881f02ac252ee19ff78c0c338c/setup.py#L287

**Comment by MeNsaaH** [comment]
Why then does it keep failing if numpy is not preinstalled? Is there some numpy functions called during setup?

**Comment by skjerns** [comment]
yes, you're right, there is some code executed before setup using numpy.

not a priority right now, as 95% of Python users probably have numpy installed already.

You're welcome to make a PR that addresses the issue!

**Comment by MeNsaaH** [comment]
Sure
