### ISSUE TITLE
CAP Sleep Database load error

### ISSUE THREAD

**Issue by mpopopa** [holgern/pyedflib#76]
Hello- I have trouble loading some of edf files uploaded in CAP sleep database (https://physionet.org/content/capslpdb/1.0.0/) with EdfReader.

While I can load "n1.edf" without error, I got the following errors to load "ins1.edf", for example: 

----> f = pyedflib.EdfReader("ins1.edf")
      
 
pyedflib/_extensions/_pyedflib.pyx in pyedflib._extensions._pyedflib.CyEdfReader.__init__()
 
pyedflib/_extensions/_pyedflib.pyx in pyedflib._extensions._pyedflib.CyEdfReader.open()
 
pyedflib/_extensions/_pyedflib.pyx in pyedflib._extensions._pyedflib.CyEdfReader.check_open_ok()
 
OSError: the file is not EDF(+) or BDF(+) compliant (Physical Minimum)

I appreciate any help on this, thanks!

**Comment by skjerns** [comment]
The header of this file seems to be broken or set incorrectly.

You can repair the header using [EDFBrowser](https://www.teuniz.net/edfbrowser/)

Tools -> Header editor -> select file -> save file

after that it should be loadable

**Comment by mpopopa** [comment]
Thanks, but is there any way to solve this with pyedflib (or some other library in python)?

**Comment by skjerns** [comment]
not with `pyedflib` I'm afraid. As far as I can see there's just a few numbers wrong indicating the length of the record. Could be fixed easily, but it's not implemented currently

I think best option to avoid manual work is to ask the creater of EDFBrowser kindly if he can implement a command line interface for header repairing. He's on [GitLab] (https://gitlab.com/Teuniz/EDFbrowser/-/issues). I'd appreciate having a command line option for this as well :) Else it should be a bit of manual work, but you'll be done within an hour. not all files are broken as I can see.

**Comment by mpopopa** [comment]
I see, thanks for your suggestions. FYI, the followings are the files that produced the error in pyedflib in loading them:

./n13.edf
./n12.edf
./n14.edf
./plm1.edf
./ins9.edf
./nfle8.edf
./nfle9.edf
./ins1.edf
./rbd16.edf
./brux1.edf
./sdb1.edf
./sdb4.edf
