### ISSUE TITLE
Implement sub-second precision of starting time

### ISSUE THREAD

**Issue by skjerns** [holgern/pyedflib#79]

**Comment by greydongilmore** [comment]
@holgern @skjerns I have reported this same issue to [MNE-python](https://github.com/mne-tools/mne-python/issues/7872#issue-632648353) and [FieldTrip](https://github.com/fieldtrip/fieldtrip/issues/1425#issue-634921091). MNE has merged a [PR](https://github.com/mne-tools/mne-python/pull/7875#issue-430338479) to the master branch already.

Not accounting for submillisecond accuracy delays all the annotation timestamps by that amount. The millisecond component of the starttime is found in the TAL channel within the first data block.

**Comment by skjerns** [comment]
@greydongilmore thanks! This library is built upon `EDFLib`, I requested the feature there and the fix was implemented. However, to make things work with `pyedflib` we need to adapt a few more things inside the C code. I've briefly discussed this at #81 but so far had no time to start this process.

**Comment by greydongilmore** [comment]
@skjerns I naively discovered these issues by cloning pyedflib and simply overwriting `edflib.c` and `edflib.h`. I should have known it wouldn't be that simple... :innocent:

**Comment by skjerns** [comment]
For many cases it should actually work out of the box with replacing edflib.c/h. But there are a few corner-cases and adaptations which need adaptation. E.g. writing vanilla EDF/BDF.
 
I'll be finished with the update today and we'll make another release shortly after that.

**Comment by greydongilmore** [comment]
@skjerns sounds good. Let me know if you want any tests run :+1:

**Comment by skjerns** [comment]
Update is done, but waiting for merge from the other repo maintainer

**Comment by skjerns** [comment]
@greydongilmore I've implemented the changes. Can you check if it works?

Test it with the dev version: `pip install git+https://github.com/holgern/pyedflib.git`

**Comment by greydongilmore** [comment]
@skjerns will do this ASAP

**Comment by greydongilmore** [comment]
@skjerns working on my end :+1:
