### ISSUE TITLE
Wrong and misleading docstring for setDatarecordDuration

### ISSUE THREAD

**Issue by fresann** [holgern/pyedflib#8]
Hey,

Just wanted to point out that the documentation for EdfWriter.setDatarecordDuration is wrong and a bit misleading. 

Looking at the corresponding function edf_set_datarecord_duration in edflib.c it is clear that the duration should be in the range 0.001 to 60 seconds, not 0.05 to 20.0 seconds. This is also documented in edflib.h.

Also, it could be good to point out that the unit of the duration is in 10 microseconds. Now you get the picture that the unit is 1 seconds. This caused me some grey hairs as I tried to set a non-integer sample rate 😄 

Appreciate your work on the library!

**Comment by holgern** [comment]
Thank you for reporting this!
