### ISSUE TITLE
Error importing pyedflib on Windows

### ISSUE THREAD

**Issue by mikylucky** [holgern/pyedflib#80]
Hi,
I get the following error when importing the library

`AttributeError: type object 'pyedflib._extensions._pyedflib.CyEdfReader' has no attribute '__reduce_cython__'`

Any clue on how to solve the issue?

The environment is:
pyEDFlib 0.1.17
numpy 1.18.4

**Comment by skjerns** [comment]
Which environment?  
How did you try to install? 
Did you try to uninstall and reinstall? 

try to install the develop version.
`pip install git+https://github.com/holgern/pyedflib`

**Comment by mikylucky** [comment]
I installed first using `pip install pyedflib` (I'm using conda)

I tried your method but nothing changed.

But I noticed a thing: on the first import attempt it gives me this error:

`ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject`

From the second run, the error is: 

`AttributeError: type object 'pyedflib._extensions._pyedflib.CyEdfReader' has no attribute '__reduce_cython__'`

**Comment by skjerns** [comment]
This doesn't seem to be a problem of `pyedflib`. If you google you find lot's of similar posts

I assume you're using Python 3?
try installing an older version of numpy `pip install numpy==1.16.1`

have you tried updating conda via `conda update --all`?

**Comment by mikylucky** [comment]
Yes, Python 3.8.2

Tried to install numpy 1.16.1, but it fails.

Tried to update all, no updates and no fix.

This is the beginning of the error throwed installing numpy 1.16.1

`pip install numpy==1.16.1
Collecting numpy==1.16.1
  Using cached numpy-1.16.1.zip (5.1 MB)
Building wheels for collected packages: numpy
  Building wheel for numpy (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\mikyl\Anaconda3\envs\eeg\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\mikyl\\AppData\\Local\\Temp\\pip-install-9e_et6i2\\numpy\\setup.py'"'"'; __file__='"'"'C:\\Users\\mikyl\\AppData\\Local\\Temp\\pip-install-9e_et6i2\\numpy\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\mikyl\AppData\Local\Temp\pip-wheel-xzrhr1j5'
       cwd: C:\Users\mikyl\AppData\Local\Temp\pip-install-9e_et6i2\numpy\
  Complete output (1673 lines):
  Running from numpy source directory.
  C:\Users\mikyl\AppData\Local\Temp\pip-install-9e_et6i2\numpy\numpy\distutils\misc_util.py:476: SyntaxWarning: "is" with a literal. Did you mean "=="?
    return is_string(s) and ('*' in s or '?' is s)
  blas_opt_info:
  blas_mkl_info:
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler`

It's too long to paste it all, but it seems something related to the C compiler

**Comment by skjerns** [comment]
Alright. Seems like it's not specific to pyedflib.

Feel free to post your solution here in case you find one.
