### ISSUE TITLE
Gender and patient name can't be properly anonymized

### ISSUE THREAD

**Issue by eniemela3** [holgern/pyedflib#87]
I am trying to write an EDF file where the header (just the file header, not the signal headers) are blank/anonymized, i.e. filled with 'X' as instructed in the EDF+ specifications. I am unable to properly set the gender and patient name.

I use EdfWriter, and tried a few approaches:
- don't use setHeader() at all
- pass empty strings for patient name and gender in setHeader()
- pass 'X' for patient name and gender in setHeader()
- use highlevel.anonymize_edf to an existing file with kwargs: to_remove=['patientname', 'gender'], new_values=['', '']

In all of the above, pyedflib writes the gender as 'F' and the name as 'X'. The name is written correctly, as EDF+ specs instruct to use 'X' for anonymization/unknown values. However, when reading the file with EdfReader and obtaining the header with getHeader(), the patient name reads as 'X'. I would expect an empty string, as 'X' is a reserved character in the spec.

The gender being written as 'F' seems to be an error during the writing of the file. I suspect that the use of [gender2int](https://github.com/holgern/pyedflib/blob/master/pyedflib/edfwriter.py#L46) is the reason for this, as the gender defaults to 0 (female). Is there a way to get around this?

**Comment by skjerns** [comment]
Hey @eniemela3 it was indeed impossible due to the way the system was setup. I changed the way `gender2int` operates and now it should work! install the master version from github to test it.

**Comment by eniemela3** [comment]
Perfect, thank you!

Do you know when the next release including this change would be available? I currently rely on pip installs, and would rather avoid building pyedflib myself.

**Comment by skjerns** [comment]
maybe @holgern can make a new release? (I don't have the pypi login-data)

**Comment by holgern** [comment]
Ok, I can make a new release.

**Comment by skjerns** [comment]
thanks alot for the fast response and new release :)

**Comment by eniemela3** [comment]
Many thanks to both of you for the quick fix and release!

I noticed that the issue with the patient name that was briefly mentioned above was probably not addressed here. I'll double check that, and create a new issue if needed.

**Comment by skjerns** [comment]
X is reserved for a header field that is empty. So if no gender is set, a X will be set. Same for the name. Let us know if you find some behaviour that is not as intended!
