### ISSUE TITLE
Not able to Read BDF File

### ISSUE THREAD

**Issue by Xpiee** [holgern/pyedflib#88]
The pyedflib.EdfReader works only for EDF files and not for BDF Files. While the library description states that it works for both of them.

**Comment by skjerns** [comment]
BDF is more or less just EDF with 24 bits. `pyedflib` has no problem reading BDF, which you can test with the official files from [biosemi](https://www.biosemi.com/download/BDFtestfiles.zip)

```
from pyedflib.highlevel import read_edf
read_edf('./Newtest17-2048.bdf')
```

If you cannot read a file it is likely that the file is either corrupt or doesn't follow the official specifications (which is unfortunately very often the case). Try opening it in EDFBrowser and let us know if it works there (EDFBrower also relies on `edflib`, which we wrap in `pyedflib`)

**Comment by Xpiee** [comment]
Thank you for your response. I have resolved the issue. There is no issue with the Library. The only thing is that 
`f = pyedflib.EdfReader("D:\EDF_signal.edf")` works but,

`f = pyedflib.EdfReader("D:\BDF_signal.bdf")` does not work. I had to replace "\\" with "/" to make it work.

**Comment by skjerns** [comment]
`\` is seen as an [escape character](https://en.wikipedia.org/wiki/Escape_character). to use it you must type `\\` in Python.
