### ISSUE TITLE
How to close an already opened file?

### ISSUE THREAD

**Issue by madhavpr** [holgern/pyedflib#9]
Hi,

I'm trying to read EEG signals and I'm quite new to this field. I ran the following script.

f = pyedflib.EdfReader("chb01_01.edf")
print(f)
n = f.signals_in_file
print("number of signals in file:", n)
signal_labels = f.getSignalLabels()
print("signal_labels:", signal_labels)

It worked fine when I ran it for the first time. However, if I run it again, I get the following error:

IOError: file has already been opened

I have tried inserting 1. f._close()  2. f._close() followed by del f, after the print("signal_labels..... ) function but failed. Is there a way to fix this error? Thanks a lot

**Comment by holgern** [comment]
Should be work now

f._close()
del f

**Comment by wmbm** [comment]
I have a similar error, such that I can neither close nor open the file as is says its both non-existent or already open 

```
f = pyedflib.EdfReader(file_path )
pyedflib/_extensions/_pyedflib.pyx in pyedflib._extensions._pyedflib.CyEdfReader.__init__()

pyedflib/_extensions/_pyedflib.pyx in pyedflib._extensions._pyedflib.CyEdfReader.open()

pyedflib/_extensions/_pyedflib.pyx in pyedflib._extensions._pyedflib.CyEdfReader.check_open_ok()

IOError: file has already been opened
```
then 

```
f._close()
del f

NameError: name 'f' is not defined
```
