### ISSUE TITLE
write_edf is very slow after a signal has been changed

### ISSUE THREAD

**Issue by DavidCEAMS** [holgern/pyedflib#92]
Hi,
I'm trying to use the high lvl API to read an EDF, filter a signal and write it back. The problem is that when I do that, the call to write_edf takes several minutes to complete (for a 400MB file).

I'd like to make sure I'm using it correctly.

Here's a sample code:
```
import pyedflib
import numpy as np
from scipy import signal

def find_channel_index(signal_headers, channel_label):
    for i, header in enumerate(signal_headers):
        if header['label'] == channel_label:
            return i
    return None

input_filename = 'subject1.edf'
output_filename = 'subject1_output.edf'
channel = 'EEG Fz'

# Open the EDF file
[signals, signal_headers, file_header] = pyedflib.highlevel.read_edf(input_filename)

# Find the channel to filter
channel_index = find_channel_index(signal_headers, channel)

# Create the filter
lf = 8
hf = 12
order = 100
sample_rate = signal_headers[channel_index]['sample_rate']
taps = signal.firwin(order, [lf, hf], pass_zero='bandpass', fs=sample_rate)

# Filter the signal
signals[channel_index] = signal.filtfilt(taps, 1, signals[channel_index])

# Write it back
pyedflib.highlevel.write_edf(output_filename, signals, signal_headers, file_header, file_type=pyedflib.FILETYPE_EDF)
```
Is this the proper way of doing it?

Thanks

**Comment by skjerns** [comment]
Can you upload the sample file to wetransfer (or dropboxlink etc) and send it to tm2v0apq1o2@temp.mailbox.org ?

**Comment by holgern** [comment]
The only way to speed up writing huge data files is to use setDatarecordDuration

f_writer.setDatarecordDuration(int(100000 * datarecord_duration))
When using this, each sample rate needs to be multiplied by it:

ch_dict['sample_rate'] = ch_dict['sample_rate'] * datarecord_duration

Maybe this would be a good addition to the high-level code.

**Comment by skjerns** [comment]
Ah, I didn't know about that. However, that means if the `datarecord_duration` is not a divisor of the length of the signal (in seconds), it will append zeros which I think it not favorable. E.g. writing a signal with length 150 seconds with `datarecord_duration=60` will write 150 seconds + 30 seconds blank.

I'll implement it such that it will only choose an appropriate `datarecord_duration`.

**Comment by holgern** [comment]
No this is the drawback, when setting datarecord_duration, but as I know the only way to speed up writing. Otherwise, writing a 400MB file takes forever (minutes to hours)

**Comment by skjerns** [comment]
I've implemented it, and the `block_size` can be overwritten to 60 if the user wants.

**Comment by DavidCEAMS** [comment]
> Should be faster than several minutes. Did you check that the hardware is not the bottleneck? is the file written on an SSD/network/USB-Stick?

The file is written on my computer on a SSD, so that isn't the problem. 

Something I forget to mention is that if I don't apply the filter, writing the file is fast, a couple seconds. It's only when a change the signal with a filter that it get really slow. You can test it with a smaller EDF file. If you remove the filter and check the elapsed time for the function write_edf, you'll see that it's always faster without the filter beforehand. The time difference is just compounded for a bigger file.

I tried digging deeper to find the problem and what I saw is that the function call blockWritePhysicalSamples (edfwriter.py) is the one slowing down. After that it goes in the C library so I couldn't debug further.

Hope it helps.

**Comment by skjerns** [comment]
Can you download the repo, checkout `speed_up_write` and install that version? check if it's now faster with larger blockwrites. maybe set `write_edf(..., block_size=60)`

**Comment by DavidCEAMS** [comment]
Thanks, I tried this version and it's much faster when I set block_size=60 (still slow with block_size=-1). That's the EDF data record size right? I wonder if there is any drawback, besides the padding at the end, of using such a big data record size.

It's still curious why a modifcation to the signal increases the write time dramatically.

**Comment by skjerns** [comment]
Yes, that's the size of each write block (60=1 minute chunks are written at a time). With `-1` it will try to find an appropiate block size such that no padding is there, probably you have an "unlucky" length.

No idea to your second question, but if you do find out, let me know, I'm curious as well!

**Comment by DavidCEAMS** [comment]
A colleague just told me that some EDF viewer do not support data record size higher than 1s. It's allowed by the spec but not common. I'm not sure we want to change the data record size of every EDF that goes through our process, especially for a workaround.

I saw you were considering using the python version of EDFLib, is that still something you have in mind? Would be easier to debug the low level API if the whole stack was in Python. I understand it might be quite an undertaking with the drawback of being potentially a bit slower. No pressure there, just curious.

**Comment by skjerns** [comment]
Mhh, good to know. Then I'll better put the default value back to 1. So far I had no problems loading it in different softwares, but I know how non-conformingly written some EDF-libraries are.

I did some preliminary tests with the Python version of pyedflib, and it's _magnitudes_ slower than the C version, so I don't think we'll be switching soon.

**Comment by DavidCEAMS** [comment]
Alright, thx for looking into it.

**Comment by holgern** [comment]
After taking a look into edffile.c, I think that the occurrence of doing fflush() could determine the write speed:
https://github.com/holgern/pyedflib/blob/master/pyedflib/_extensions/c/edflib.c#L4985
When increasing datarecord_duration > 1, fflush() is called less often which could explain the speed up.

**Comment by DavidCEAMS** [comment]
Alright, I did some more test and apparently this line here is wrong:

`signals[channel_index] = signal.filtfilt(taps, 1, signals[channel_index])`

It changes the reference of the array to point to the one returned by the function filtfilt.

I should instead copy the samples:
```
filtered_signal = signal.filtfilt(taps, 1, signals[channel_index])
signals[channel_index] = filtered_signal.copy()
```
Or like this:
```
filtered_signal = signal.filtfilt(taps, 1, signals[channel_index])
signals[channel_index][:] = filtered_signal[:]
```
I can't explain why it works faster this way but now saving a 400Mo EDF files takes 6 seconds instead of multiple minutes. If anyone knows what's happening behind the scene, I'd love to know.

Live and learn.

**Comment by skjerns** [comment]
Followup: I think the problem lies within which memory order the array of question uses. As edflib is a C library, it plays nicely with C layout. If the array is in Fortran order, the write speed is much much slower.

**Comment by LucaCerina** [comment]
Hi, I was having the same problem and I got to this thread. I noticed in the Numpy docs that isFortran seems to be unreliable  (https://numpy.org/devdocs/reference/generated/numpy.isfortran.html?highlight=isfortran#numpy.isfortran).

We could do a ravel/copy anyway on those signal to prevent false flags, because I noticed that also 1-D arrays with shape (N,) confuse these f_contiguous and c_contiguous flags when are copied from columns of a 2-D array

**Comment by skjerns** [comment]
sounds like a healthy fix! so you propose to run a `ravel` on all input and reshape accordingly, just for safety?

**Comment by LucaCerina** [comment]
It's done anyway in writeSamples as `data_list[i]. ravel` so we can move it from there. 
I don't know the EDF standard in details but I guess it's a valid assumption that all channels are 1-D right? As not breaking any rule by using `ravel` on all signals

**Comment by skjerns** [comment]
Yes, that assumption is correct! Do you want to do a PR (and if necessary some sanity-check-tests?)? :)
