### ISSUE TITLE
Problem importing pyedflib

### ISSUE THREAD

**Issue by hadassa2807** [holgern/pyedflib#94]
Hi, 

I installed the latest released pyedflib (with version of numpy 1.19.2 and python 3.7), and I ran a test on the setup (with the command python setup.py test) and everything is ok. But I keep getting the following error while trying to import the library:

ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 124 from C header, got 112 from PyObject

How can I fix this ?

Thanks in advance !

**Comment by skjerns** [comment]
Have you tried installing via pip from pypi, i.e. `pip install pyedflib`, does that work?

Is there more information about the error, or is that all you are given? Else than that my guess is that this is a problem with numpy, and not with `pyedflib`. Have you tried reinstalling numpy?

**Comment by hadassa2807** [comment]
Thanks for your answer, here is the whole error I get: 

Traceback (most recent call last):
  File "C:\Users\Hadassa-Port\Downloads\Python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Hadassa-Port\Downloads\Python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Hadassa-Port\Desktop\semester7\ProjectA\Codes\<file_name>", line 4, in <module>
    import pyedflib
  File "C:\Users\Hadassa-Port\Downloads\Python37-32\lib\site-packages\pyedflib\__init__.py", line 11, in <module>
    from ._extensions._pyedflib import *
  File "pyedflib\_extensions\_pyedflib.pyx", line 1, in init pyedflib._extensions._pyedflib
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 124 from C header, got 112 from PyObject

Regarding the solutions you suggested: 

- I tried installing the release and got an "all requirements are satisfied" output
- Reinstalling numpy and its previous version brings the same error (tried both separately)

**Comment by skjerns** [comment]
try removing `pyedflib`, and then install via pip:

```
pip uninstall pyedflib
pip install pyedflib --force-reinstall
```

**Comment by hadassa2807** [comment]
Done right now, and still getting the same error :(...

**Comment by hadassa2807** [comment]
Problem fixed !!
By adding "python -m" before what you suggested:

python -m pip uninstall pyedflib
python -m pip install pyedflib --force-reinstall

Thanks a lot for your help !!
