### ISSUE TITLE
The pyedflib File Package does not support Chinese path

### ISSUE THREAD

**Issue by ddbbqqpp** [holgern/pyedflib#99]
```
from pyedflib import highlevel

file_path = 'D:/sleep/sleep-edf/chinese.edf'
# file_path = 'D:/sleep/sleep-edf/中文.edf'
signals, signal_headers, header = highlevel.read_edf(file_path)

print(signals)
print(signal_headers)
print(header)
```

**ERROR**

  # file_path = 'D:/sleep/sleep-edf/中文.edf'

```
  with pyedflib.EdfReader(edf_file) as f:
  File "pyedflib\_extensions\_pyedflib.pyx", line 116, in pyedflib._extensions._pyedflib.CyEdfReader.__init__
  File "pyedflib\_extensions\_pyedflib.pyx", line 156, in pyedflib._extensions._pyedflib.CyEdfReader.open
  File "pyedflib\_extensions\_pyedflib.pyx", line 128, in pyedflib._extensions._pyedflib.CyEdfReader.check_open_ok
  OSError: D:/sleep/sleep-edf/中文edf: can not open file, no such file or directory
```

**Comment by skjerns** [comment]
This is a problem with Windows not using UTF-8 encoding (it works on my machine).

You can enable UTF-8 support on your Windows machine like this: https://superuser.com/questions/1424009/changing-ansi-and-oem-code-page-in-windows

However, this is a bug that we are aware of and it happens during the execution of the C code that is wrapped. Python is native UTF-8, but the C plugin handles encodings according to the system locale. If the system locale is not UTF8 it will wrongly decode the filename and not find it.

**Comment by ddbbqqpp** [comment]
> This is a problem with Windows not using UTF-8 encoding (it works on my machine when I just tried it).
> 
> You can enable UTF-8 support on your Windows machine like this: https://superuser.com/questions/1424009/changing-ansi-and-oem-code-page-in-windows
> 
> Let me know if it worked.
> 
> However, this is a bug that we are aware of and it happens during the execution of the C code that is wrapped. Python is native UTF-8, but the C plugin handles encodings according to the system locale. If the system locale is not UTF8 it will wrongly decode the filename and not find it.

but I can open **"D:/sleep/sleep-edf/中文.edf"** with edfbrowser or mne-python

https://github.com/mne-tools/mne-python
https://www.teuniz.net/edfbrowser/index.html

**Comment by skjerns** [comment]
Yes, because they are either purely in python (utf8) or purely in C (edfbrowser,. using system locale), i.e. there is no conversion from one encoding system into another happening.

As said, I'm aware of the problem, I tried to fix it once, but this had sideeffects, I'll look into it again soon.

**Comment by ddbbqqpp** [comment]
> Yes, because they are either purely in python (mne, utf8) or purely in C (edfbrowser, using system locale), i.e. there is no conversion from one encoding system into another happening.
> 
> As said, I'm aware of the problem, I tried to fix it once, but this had side effects on other OSs than Windows, which I could not easily debug as I don't have a unix disto running, I'll look into it again soon. In principle it should be fixable, but it has probably to happen on the C code, and that is always a bit trickier to tackle correctly than Python. Our tests also only cover the Python code directly and not the C code, so changing something there is always more risky. related: #30 and #77
> 
> Until then please consider enabling UTF8 as a locale for Windows. I have it enabled and one year later I did not have any negative side effects.

If this problem is tricky, Can we ask the author of EDFbrowser, It's very important for us to solve the coding problem
https://gitlab.com/Teuniz

**Comment by skjerns** [comment]
No, please don't, he's not responsible for this project, only for the library that we port (`edflib` is also by him). 

Until I find time to fix it (possibly next week?), consider one of the following workarounds:

* copy the files before within Python to a temporary location with regular ASCII encoded filename (e.g. `shutil.copy('D:/sleep/sleep-edf/中文edf', 'tmp.edf'); highlevel.read_edf('tmp.edf'))`)
* just use `mne` or `Python-edflib` (by Teuniz ;) https://www.teuniz.net/edflib_python/index.html )
* Change the Windows locale to use [UTF8 as suggested above](https://superuser.com/questions/1424009/changing-ansi-and-oem-code-page-in-windows)

**Comment by skjerns** [comment]
The issue is even far more complicated than I thought. However, I created a workaround that should do the trick, see here: https://github.com/holgern/pyedflib/pull/100

By the way: EDFBrowser cannot open the file on my system as well, when I disable UTF8-support.

However, I would advise you to just enable UTF8 for Windows, it makes things much easier.

**Comment by skjerns** [comment]
@ddbbqqpp can you install the dev version from master and check if it works now?

`pip install git+https://github.com/holgern/pyedflib.git`

**Comment by ddbbqqpp** [comment]
> @ddbbqqpp can you install the dev version from master and check if it works now?
> 
> `pip install git+https://github.com/holgern/pyedflib.git`

It's really great to solve the path file problem, I've tested it
Thanks! You are really wonderful! @skjerns
